# SFC, FC & SC - LOBE vs HCP #

In [2]:
## temporary
#temporary:
subjects = {
    dataset: list(
        pd.read_csv(
            f"resources/dataset-{dataset}_subjects.tsv",
            sep="\t",
            dtype={"participant_label": str},
        ).participant_label
    )
    for dataset in ['HCP','LOBE']
}

In [42]:
subjects

{'HCP': ['HCD0001305',
  'HCD0021614',
  'HCD0026119',
  'HCD0041822',
  'HCD0042420',
  'HCD0051825',
  'HCD0059235',
  'HCD0069238',
  'HCD0075435',
  'HCD0110411',
  'HCD0111716',
  'HCD0118528',
  'HCD0119429',
  'HCD0121719',
  'HCD0123925',
  'HCD0129937',
  'HCD0134526',
  'HCD0143426',
  'HCD0146331',
  'HCD0147333',
  'HCD0152932',
  'HCD0154431',
  'HCD0174235',
  'HCD0182941',
  'HCD0183438',
  'HCD0183539',
  'HCD0185442',
  'HCD0185644',
  'HCD0197045',
  'HCD0197348',
  'HCD0214423',
  'HCD0215829',
  'HCD0224123',
  'HCD0232223',
  'HCD0236635',
  'HCD0245030',
  'HCD0247438',
  'HCD0248440',
  'HCD0259546',
  'HCD0263032',
  'HCD0267747',
  'HCD0276243',
  'HCD0277447',
  'HCD0295146',
  'HCD0298758',
  'HCD0311118',
  'HCD0330021',
  'HCD0338744',
  'HCD0353538',
  'HCD0370639',
  'HCD0392144',
  'HCD0392649',
  'HCD0393550',
  'HCD0425335',
  'HCD0461844',
  'HCD0462341',
  'HCD0469658',
  'HCD0471746',
  'HCD0476352',
  'HCD0486254',
  'HCD0504735',
  'HCD0505838',
  'HCD0514738',
  'HCD0515538',
  'HCD0519849',
  'HCD0526644',
  'HCD0528850',
  'HCD0534138',
  'HCD0536142',
  'HCD0541539',
  'HCD0551946',
  'HCD0555146',
  'HCD0576558',
  'HCD0577661',
  'HCD0583555',
  'HCD0605135',
  'HCD0605438',
  'HCD0616342',
  'HCD0621638',
  'HCD0641341',
  'HCD0643345',
  'HCD0644044',
  'HCD0664656',
  'HCD0667763',
  'HCD0678970',
  'HCD0682557',
  'HCD0684460',
  'HCD0686666',
  'HCD0703943',
  'HCD0758867',
  'HCD0777265',
  'HCD0784060',
  'HCD0789272',
  'HCD0796067',
  'HCD0797877',
  'HCD0802440',
  'HCD0804545',
  'HCD0808654',
  'HCD0810035',
  'HCD0812241',
  'HCD0822850',
  'HCD0842250',
  'HCD0845458',
  'HCD0848060',
  'HCD0857566',
  'HCD0858467',
  'HCD0869371',
  'HCD0891566',
  'HCD0894875',
  'HCD0904650',
  'HCD0921145',
  'HCD0925759',
  'HCD0933051',
  'HCD0946868',
  'HCD0956871',
  'HCD0969072',
  'HCD0977576',
  'HCD0979378',
  'HCD0988682',
  'HCD0997380',
  'HCD1003617',
  'HCD1007423',
  'HCD1010311',
  'HCD1010412',
  'HCD1017729',
  'HCD1017931',
  'HCD1022722',
  'HCD1029837',
  'HCD1039032',
  'HCD1093139',
  'HCD1103419',
  'HCD1106728',
  'HCD1108833',
  'HCD1111822',
  'HCD1113220',
  'HCD1120015',
  'HCD1123526',
  'HCD1129235',
  'HCD1139541',
  'HCD1159446',
  'HCD1162334',
  'HCD1181843',
  'HCD1184950',
  'HCD1187653',
  'HCD1196553',
  'HCD1203928',
  'HCD1205326',
  'HCD1215632',
  'HCD1221627',
  'HCD1227134',
  'HCD1231832',
  'HCD1239343',
  'HCD1240530',
  'HCD1262136',
  'HCD1267348',
  'HCD1282142',
  'HCD1289358',
  'HCD1293349',
  'HCD1305936',
  'HCD1306130',
  'HCD1328241',
  'HCD1328948',
  'HCD1346849',
  'HCD1350638',
  'HCD1375755',
  'HCD1380849',
  'HCD1389665',
  'HCD1396662',
  'HCD1400728',
  'HCD1404231',
  'HCD1410933',
  'HCD1411632',
  'HCD1411935',
  'HCD1435646',
  'HCD1445245',
  'HCD1456048',
  'HCD1458153',
  'HCD1464451',
  'HCD1464653',
  'HCD1477056',
  'HCD1479262',
  'HCD1479969',
  'HCD1490048',
  'HCD1491252',
  'HCD1500025',
  'HCD1504437',
  'HCD1518448',
  'HCD1527045',
  'HCD1534244',
  'HCD1553551',
  'HCD1568867',
  'HCD1575359',
  'HCD1581455',
  'HCD1590860',
  'HCD1610436',
  'HCD1612238',
  'HCD1622342',
  'HCD1630139',
  'HCD1633751',
  'HCD1646154',
  'HCD1647863',
  'HCD1658969',
  'HCD1664762',
  'HCD1681257',
  'HCD1685164',
  'HCD1686267',
  'HCD1694569',
  'HCD1714852',
  'HCD1783366',
  'HCD1785572',
  'HCD1787677',
  'HCD1791163',
  'HCD1794977',
  'HCD1801140',
  'HCD1812044',
  'HCD1842558',
  'HCD1845160',
  'HCD1855365',
  'HCD1856468',
  'HCD1863465',
  'HCD1871969',
  'HCD1872971',
  'HCD1880162',
  'HCD1880465',
  'HCD1881164',
  'HCD1886275',
  'HCD1886477',
  'HCD1886881',
  'HCD1892371',
  'HCD1900142',
  'HCD1903350',
  'HCD1905152',
  'HCD1906457',
  'HCD1928871',
  'HCD1930353',
  'HCD1933864',
  'HCD1946469',
  'HCD1969986',
  'HCD1978987',
  'HCD1983879',
  'HCD1985378',
  'HCD1986784',
  'HCD1992375',
  'HCD1994884',
  'HCD2000111',
  'HCD2001517',
  'HCD2008329',
  'HCD2046842',
  'HCD2046943',
  'HCD2055237',
  'HCD2062537',
  'HCD2063034',
  'HCD2068145',
  'HCD2073340',
  'HCD2099257',
  'HCD2109638',
  'HCD2133433',
  'HCD2134031',
  'HCD2140127',
  'HCD2156142',
  'HCD2156344',
  'HCD2163644',
  'HCD2164242',
  'HCD2181848',
  'HCD2203933',
  'HCD2207840',
  'HCD2211932',
  'HCD2216437',
  'HCD2229547',
  'HCD2239247',
  'HCD2240030',
  'HCD2254243',
  'HCD2286155',
  'HCD2300426',
  'HCD2301428',
  'HCD2302430',
  'HCD2304737',
  'HCD2342745',
  'HCD2344244',
  'HCD2370952',
  'HCD2380753',
  'HCD2383456',
  'HCD2383658',
  'HCD2400026',
  'HCD2400632',
  'HCD2428755',
  'HCD2449763',
  'HCD2485666',
  'HCD2491257',
  'HCD2496570',
  'HCD2504038',
  'HCD2523345',
  'HCD2524751',
  'HCD2540648',
  'HCD2543250',
  'HCD2581763',
  'HCD2594671',
  'HCD2594772',
  'HCD2606652',
  'HCD2633554',
  'HCD2655766',
  'HCD2669575',
  'HCD2685169',
  'HCD2704551',
  'HCD2711649',
  'HCD2714655',
  'HCD2715152',
  'HCD2737869',
  'HCD2743157',
  'HCD2748268',
  'HCD2748672',
  'HCD2751560',
  'HCD2751964',
  'HCD2754061',
  'HCD2757370',
  'HCD2761967',
  'HCD2762565',
  'HCD2785678',
  'HCD2786074',
  'HCD2797584',
  'HCD2807460',
  'HCD2810954',
  'HCD2811552',
  'HCD2812352',
  'HCD2828569',
  'HCD2855875',
  'HCD2856170',
  'HCD2878382',
  'HCD2879788',
  'HCD2884175',
  'HCD2901654',
  'HCD2904862',
  'HCD2905460',
  'HCD2930055',
  'HCD2932665',
  'HCD2936875',
  'HCD2939275',
  'HCD2945876',
  'HCD2957277',
  'HCD2976382',
  'HCD2990073'],
 'LOBE': ['004',
  '006',
  '007',
  '009',
  '010',
  '012',
  '013',
  '014',
  '015',
  '017',
  '019',
  '020',
  '021',
  '022',
  '024',
  '025',
  '026',
  '027',
  '028',
  '029',
  '031',
  '033',
  '035',
  '036',
  '038',
  '040',
  '041']}

In [98]:
subjects=snakemake.params.subjects

NameError: name 'snakemake' is not defined

## Importing packages and setting paths ##

In [1]:
import pandas as pd
import nibabel as nib
from glob import glob
import numpy as np

In [100]:
#print(f"snakemake.params.subjects[{dataset}] = {snakemake.params.subjects[dataset]}")

In [3]:
#first load up the label dseg table
atlas='brainnetome'

df_labels = pd.read_csv(f'resources/atlas/atlas-{atlas}_dseg.tsv',sep='\t')
df_labels

df_network_names = df_labels.networks.unique()
df_network_names

#df_tabular = pd.read_csv(snakemake.input.tsv,sep='\t')
df_tabular = pd.read_csv('resources/merged_tabular.tsv',sep='\t')

#df_tabular = pd.read_csv('results/analysis/df_tabular.csv',sep='\t')

df_tabular

,participant_id,dataset,age,sex,age_seizure_onset,age_ep_diagnosis,ep_duration_first_scan,seizure_duration_first_scan,pnes,benign_rolandic,...,loc_pet_occipital,loc_pet_parietal,loc_pet_temporal,loc_semiology,loc_final_frontal,loc_final_occipital,loc_final_parietal,loc_final_temporal,loc_final_temporal_plus,loc_final_extratemporal
0,sub-HCD0001305,HCP,11.916667,M,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,sub-HCD0021614,HCP,9.166667,F,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,sub-HCD0026119,HCP,15.166667,F,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,sub-HCD0041822,HCP,17.416667,M,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,sub-HCD0042420,HCP,18.333333,M,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
363,sub-035,LOBE,7.000000,M,2.0,4.0,3.0,5.0,0.0,0.0,...,NaN,NaN,NaN,NaN,1,0,0,0,0.0,0.0
364,sub-036,LOBE,15.000000,M,10.0,NaN,NaN,5.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
365,sub-038,LOBE,10.000000,F,7.0,7.0,3.0,3.0,0.0,0.0,...,NaN,NaN,NaN,parietal,0,0,1,0,0.0,0.0
366,sub-040,LOBE,9.000000,F,5.0,NaN,NaN,4.0,NaN,NaN,...,NaN,NaN,NaN,NaN,unknown,unknown,unknown,unknown,NaN,NaN
367,sub-041,LOBE,12.000000,M,4.0,NaN,NaN,8.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN

In [4]:
# Schaefer Patterns
#fc_pattern='results/{dataset}/sub-{subject}/func/sub-{subject}_task-rest_den-91k_desc-preproc_denoise-24HMP8PhysSpikeReg_fwhm-5_atlas-schaefer_bold.pconn.nii'
#sc_pattern='results/{dataset}/sub-{subject}/dwi/sub-{subject}_den-91k_atlas-schaefer_struc.pconn.nii'
#sfc_pattern='results/{dataset}/sub-{subject}/func/sub-{subject}_task-rest_den-91k_desc-preproc_denoise-24HMP8PhysSpikeReg_fwhm-5_atlas-schaefer_sfc.pscalar.nii'

# Brainnetome Patterns
# Schaefer Patterns
fc_pattern='results/{dataset}/sub-{subject}/func/sub-{subject}_task-rest_den-91k_desc-preproc_denoise-24HMP8PhysSpikeReg_fwhm-5_atlas-brainnetome_bold.pconn.nii'
sc_pattern='results/{dataset}/sub-{subject}/dwi/sub-{subject}_den-91k_atlas-brainnetome_struc.pconn.nii'
sfc_pattern='results/{dataset}/sub-{subject}/func/sub-{subject}_task-rest_den-91k_desc-preproc_denoise-24HMP8PhysSpikeReg_fwhm-5_atlas-brainnetome_sfc.pscalar.nii'

In [5]:
sfc_paths={ dataset: sorted([sfc_pattern.format(dataset=dataset,subject=subject) for subject in subjects[dataset]]) 
               for dataset in subjects.keys() }

fc_paths={ dataset: sorted([fc_pattern.format(dataset=dataset,subject=subject) for subject in subjects[dataset]]) 
               for dataset in subjects.keys() }

sc_paths={ dataset: sorted([sc_pattern.format(dataset=dataset,subject=subject) for subject in subjects[dataset]]) 
               for dataset in subjects.keys() }

In [6]:
print(sfc_paths)

{'HCP': ['results/HCP/sub-HCD0001305/func/sub-HCD0001305_task-rest_den-91k_desc-preproc_denoise-24HMP8PhysSpikeReg_fwhm-5_atlas-brainnetome_sfc.pscalar.nii', 'results/HCP/sub-HCD0021614/func/sub-HCD0021614_task-rest_den-91k_desc-preproc_denoise-24HMP8PhysSpikeReg_fwhm-5_atlas-brainnetome_sfc.pscalar.nii', 'results/HCP/sub-HCD0026119/func/sub-HCD0026119_task-rest_den-91k_desc-preproc_denoise-24HMP8PhysSpikeReg_fwhm-5_atlas-brainnetome_sfc.pscalar.nii', 'results/HCP/sub-HCD0041822/func/sub-HCD0041822_task-rest_den-91k_desc-preproc_denoise-24HMP8PhysSpikeReg_fwhm-5_atlas-brainnetome_sfc.pscalar.nii', 'results/HCP/sub-HCD0042420/func/sub-HCD0042420_task-rest_den-91k_desc-preproc_denoise-24HMP8PhysSpikeReg_fwhm-5_atlas-brainnetome_sfc.pscalar.nii', 'results/HCP/sub-HCD0051825/func/sub-HCD0051825_task-rest_den-91k_desc-preproc_denoise-24HMP8PhysSpikeReg_fwhm-5_atlas-brainnetome_sfc.pscalar.nii', 'results/HCP/sub-HCD0059235/func/sub-HCD0059235_task-rest_den-91k_desc-preproc_denoise-24HMP8PhysSpikeReg_fwhm-5_atlas-brainnetome_sfc.pscalar.nii', 'results/HCP/sub-HCD0069238/func/sub-HCD0069238_task-rest_den-91k_desc-preproc_denoise-24HMP8PhysSpikeReg_fwhm-5_atlas-brainnetome_sfc.pscalar.nii', 'results/HCP/sub-HCD0075435/func/sub-HCD0075435_task-rest_den-91k_desc-preproc_denoise-24HMP8PhysSpikeReg_fwhm-5_atlas-brainnetome_sfc.pscalar.nii', 'results/HCP/sub-HCD0110411/func/sub-HCD0110411_task-rest_den-91k_desc-preproc_denoise-24HMP8PhysSpikeReg_fwhm-5_atlas-brainnetome_sfc.pscalar.nii', 'results/HCP/sub-HCD0111716/func/sub-HCD0111716_task-rest_den-91k_desc-preproc_denoise-24HMP8PhysSpikeReg_fwhm-5_atlas-brainnetome_sfc.pscalar.nii', 'results/HCP/sub-HCD0118528/func/sub-HCD0118528_task-rest_den-91k_desc-preproc_denoise-24HMP8PhysSpikeReg_fwhm-5_atlas-brainnetome_sfc.pscalar.nii', 'results/HCP/sub-HCD0119429/func/sub-HCD0119429_task-rest_den-91k_desc-preproc_denoise-24HMP8PhysSpikeReg_fwhm-5_atlas-brainnetome_sfc.pscalar.nii', 'results/HCP/sub-HCD0121719/func/sub-HCD0121719_task-rest_den-91k_desc-preproc_denoise-24HMP8PhysSpikeReg_fwhm-5_atlas-brainnetome_sfc.pscalar.nii', 'results/HCP/sub-HCD0123925/func/sub-HCD0123925_task-rest_den-91k_desc-preproc_denoise-24HMP8PhysSpikeReg_fwhm-5_atlas-brainnetome_sfc.pscalar.nii', 'results/HCP/sub-HCD0129937/func/sub-HCD0129937_task-rest_den-91k_desc-preproc_denoise-24HMP8PhysSpikeReg_fwhm-5_atlas-brainnetome_sfc.pscalar.nii', 'results/HCP/sub-HCD0134526/func/sub-HCD0134526_task-rest_den-91k_desc-preproc_denoise-24HMP8PhysSpikeReg_fwhm-5_atlas-brainnetome_sfc.pscalar.nii', 'results/HCP/sub-HCD0143426/func/sub-HCD0143426_task-rest_den-91k_desc-preproc_denoise-24HMP8PhysSpikeReg_fwhm-5_atlas-brainnetome_sfc.pscalar.nii', 'results/HCP/sub-HCD0146331/func/sub-HCD0146331_task-rest_den-91k_desc-preproc_denoise-24HMP8PhysSpikeReg_fwhm-5_atlas-brainnetome_sfc.pscalar.nii', 'results/HCP/sub-HCD0147333/func/sub-HCD0147333_task-rest_den-91k_desc-preproc_denoise-24HMP8PhysSpikeReg_fwhm-5_atlas-brainnetome_sfc.pscalar.nii', 'results/HCP/sub-HCD0152932/func/sub-HCD0152932_task-rest_den-91k_desc-preproc_denoise-24HMP8PhysSpikeReg_fwhm-5_atlas-brainnetome_sfc.pscalar.nii', 'results/HCP/sub-HCD0154431/func/sub-HCD0154431_task-rest_den-91k_desc-preproc_denoise-24HMP8PhysSpikeReg_fwhm-5_atlas-brainnetome_sfc.pscalar.nii', 'results/HCP/sub-HCD0174235/func/sub-HCD0174235_task-rest_den-91k_desc-preproc_denoise-24HMP8PhysSpikeReg_fwhm-5_atlas-brainnetome_sfc.pscalar.nii', 'results/HCP/sub-HCD0182941/func/sub-HCD0182941_task-rest_den-91k_desc-preproc_denoise-24HMP8PhysSpikeReg_fwhm-5_atlas-brainnetome_sfc.pscalar.nii', 'results/HCP/sub-HCD0183438/func/sub-HCD0183438_task-rest_den-91k_desc-preproc_denoise-24HMP8PhysSpikeReg_fwhm-5_atlas-brainnetome_sfc.pscalar.nii', 'results/HCP/sub-HCD0183539/func/sub-HCD0183539_task-rest_den-91k_desc-preproc_denoise-24HMP8PhysSpikeReg_fwhm-5_atlas-brainnetome_sfc.pscalar.nii', 'results/HCP/sub-HCD0185442/func/sub-HCD0185442_task-rest_den-91k_desc-preproc_denoise-24HMP8PhysSpikeReg_fwhm-5_atlas-brainnetome_sfc.pscalar.nii', 'results/HCP/sub-HCD0185644/func/sub-HCD0185644_task-rest_den-91k_desc-preproc_denoise-24HMP8PhysSpikeReg_fwhm-5_atlas-brainnetome_sfc.pscalar.nii', 'results/HCP/sub-HCD0197045/func/sub-HCD0197045_task-rest_den-91k_desc-preproc_denoise-24HMP8PhysSpikeReg_fwhm-5_atlas-brainnetome_sfc.pscalar.nii', 'results/HCP/sub-HCD0197348/func/sub-HCD0197348_task-rest_den-91k_desc-preproc_denoise-24HMP8PhysSpikeReg_fwhm-5_atlas-brainnetome_sfc.pscalar.nii', 'results/HCP/sub-HCD0214423/func/sub-HCD0214423_task-rest_den-91k_desc-preproc_denoise-24HMP8PhysSpikeReg_fwhm-5_atlas-brainnetome_sfc.pscalar.nii', 'results/HCP/sub-HCD0215829/func/sub-HCD0215829_task-rest_den-91k_desc-preproc_denoise-24HMP8PhysSpikeReg_fwhm-5_atlas-brainnetome_sfc.pscalar.nii', 'results/HCP/sub-HCD0224123/func/sub-HCD0224123_task-rest_den-91k_desc-preproc_denoise-24HMP8PhysSpikeReg_fwhm-5_atlas-brainnetome_sfc.pscalar.nii', 'results/HCP/sub-HCD0232223/func/sub-HCD0232223_task-rest_den-91k_desc-preproc_denoise-24HMP8PhysSpikeReg_fwhm-5_atlas-brainnetome_sfc.pscalar.nii', 'results/HCP/sub-HCD0236635/func/sub-HCD0236635_task-rest_den-91k_desc-preproc_denoise-24HMP8PhysSpikeReg_fwhm-5_atlas-brainnetome_sfc.pscalar.nii', 'results/HCP/sub-HCD0245030/func/sub-HCD0245030_task-rest_den-91k_desc-preproc_denoise-24HMP8PhysSpikeReg_fwhm-5_atlas-brainnetome_sfc.pscalar.nii', 'results/HCP/sub-HCD0247438/func/sub-HCD0247438_task-rest_den-91k_desc-preproc_denoise-24HMP8PhysSpikeReg_fwhm-5_atlas-brainnetome_sfc.pscalar.nii', 'results/HCP/sub-HCD0248440/func/sub-HCD0248440_task-rest_den-91k_desc-preproc_denoise-24HMP8PhysSpikeReg_fwhm-5_atlas-brainnetome_sfc.pscalar.nii', 'results/HCP/sub-HCD0259546/func/sub-HCD0259546_task-rest_den-91k_desc-preproc_denoise-24HMP8PhysSpikeReg_fwhm-5_atlas-brainnetome_sfc.pscalar.nii', 'results/HCP/sub-HCD0263032/func/sub-HCD0263032_task-rest_den-91k_desc-preproc_denoise-24HMP8PhysSpikeReg_fwhm-5_atlas-brainnetome_sfc.pscalar.nii', 'results/HCP/sub-HCD0267747/func/sub-HCD0267747_task-rest_den-91k_desc-preproc_denoise-24HMP8PhysSpikeReg_fwhm-5_atlas-brainnetome_sfc.pscalar.nii', 'results/HCP/sub-HCD0276243/func/sub-HCD0276243_task-rest_den-91k_desc-preproc_denoise-24HMP8PhysSpikeReg_fwhm-5_atlas-brainnetome_sfc.pscalar.nii', 'results/HCP/sub-HCD0277447/func/sub-HCD0277447_task-rest_den-91k_desc-preproc_denoise-24HMP8PhysSpikeReg_fwhm-5_atlas-brainnetome_sfc.pscalar.nii', 'results/HCP/sub-HCD0295146/func/sub-HCD0295146_task-rest_den-91k_desc-preproc_denoise-24HMP8PhysSpikeReg_fwhm-5_atlas-brainnetome_sfc.pscalar.nii', 'results/HCP/sub-HCD0298758/func/sub-HCD0298758_task-rest_den-91k_desc-preproc_denoise-24HMP8PhysSpikeReg_fwhm-5_atlas-brainnetome_sfc.pscalar.nii', 'results/HCP/sub-HCD0311118/func/sub-HCD0311118_task-rest_den-91k_desc-preproc_denoise-24HMP8PhysSpikeReg_fwhm-5_atlas-brainnetome_sfc.pscalar.nii', 'results/HCP/sub-HCD0330021/func/sub-HCD0330021_task-rest_den-91k_desc-preproc_denoise-24HMP8PhysSpikeReg_fwhm-5_atlas-brainnetome_sfc.pscalar.nii', 'results/HCP/sub-HCD0338744/func/sub-HCD0338744_task-rest_den-91k_desc-preproc_denoise-24HMP8PhysSpikeReg_fwhm-5_atlas-brainnetome_sfc.pscalar.nii', 'results/HCP/sub-HCD0353538/func/sub-HCD0353538_task-rest_den-91k_desc-preproc_denoise-24HMP8PhysSpikeReg_fwhm-5_atlas-brainnetome_sfc.pscalar.nii', 'results/HCP/sub-HCD0370639/func/sub-HCD0370639_task-rest_den-91k_desc-preproc_denoise-24HMP8PhysSpikeReg_fwhm-5_atlas-brainnetome_sfc.pscalar.nii', 'results/HCP/sub-HCD0392144/func/sub-HCD0392144_task-rest_den-91k_desc-preproc_denoise-24HMP8PhysSpikeReg_fwhm-5_atlas-brainnetome_sfc.pscalar.nii', 'results/HCP/sub-HCD0392649/func/sub-HCD0392649_task-rest_den-91k_desc-preproc_denoise-24HMP8PhysSpikeReg_fwhm-5_atlas-brainnetome_sfc.pscalar.nii', 'results/HCP/sub-HCD0393550/func/sub-HCD0393550_task-rest_den-91k_desc-preproc_denoise-24HMP8PhysSpikeReg_fwhm-5_atlas-brainnetome_sfc.pscalar.nii', 'results/HCP/sub-HCD0425335/func/sub-HCD0425335_task-rest_den-91k_desc-preproc_denoise-24HMP8PhysSpikeReg_fwhm-5_atlas-brainnetome_sfc.pscalar.nii', 'results/HCP/sub-HCD0461844/func/sub-HCD0461844_task-rest_den-91k_desc-preproc_denoise-24HMP8PhysSpikeReg_fwhm-5_atlas-brainnetome_sfc.pscalar.nii', 'results/HCP/sub-HCD0462341/func/sub-HCD0462341_task-rest_den-91k_desc-preproc_denoise-24HMP8PhysSpikeReg_fwhm-5_atlas-brainnetome_sfc.pscalar.nii', 'results/HCP/sub-HCD0469658/func/sub-HCD0469658_task-rest_den-91k_desc-preproc_denoise-24HMP8PhysSpikeReg_fwhm-5_atlas-brainnetome_sfc.pscalar.nii', 'results/HCP/sub-HCD0471746/func/sub-HCD0471746_task-rest_den-91k_desc-preproc_denoise-24HMP8PhysSpikeReg_fwhm-5_atlas-brainnetome_sfc.pscalar.nii', 'results/HCP/sub-HCD0476352/func/sub-HCD0476352_task-rest_den-91k_desc-preproc_denoise-24HMP8PhysSpikeReg_fwhm-5_atlas-brainnetome_sfc.pscalar.nii', 'results/HCP/sub-HCD0486254/func/sub-HCD0486254_task-rest_den-91k_desc-preproc_denoise-24HMP8PhysSpikeReg_fwhm-5_atlas-brainnetome_sfc.pscalar.nii', 'results/HCP/sub-HCD0504735/func/sub-HCD0504735_task-rest_den-91k_desc-preproc_denoise-24HMP8PhysSpikeReg_fwhm-5_atlas-brainnetome_sfc.pscalar.nii', 'results/HCP/sub-HCD0505838/func/sub-HCD0505838_task-rest_den-91k_desc-preproc_denoise-24HMP8PhysSpikeReg_fwhm-5_atlas-brainnetome_sfc.pscalar.nii', 'results/HCP/sub-HCD0514738/func/sub-HCD0514738_task-rest_den-91k_desc-preproc_denoise-24HMP8PhysSpikeReg_fwhm-5_atlas-brainnetome_sfc.pscalar.nii', 'results/HCP/sub-HCD0515538/func/sub-HCD0515538_task-rest_den-91k_desc-preproc_denoise-24HMP8PhysSpikeReg_fwhm-5_atlas-brainnetome_sfc.pscalar.nii', 'results/HCP/sub-HCD0519849/func/sub-HCD0519849_task-rest_den-91k_desc-preproc_denoise-24HMP8PhysSpikeReg_fwhm-5_atlas-brainnetome_sfc.pscalar.nii', 'results/HCP/sub-HCD0526644/func/sub-HCD0526644_task-rest_den-91k_desc-preproc_denoise-24HMP8PhysSpikeReg_fwhm-5_atlas-brainnetome_sfc.pscalar.nii', 'results/HCP/sub-HCD0528850/func/sub-HCD0528850_task-rest_den-91k_desc-preproc_denoise-24HMP8PhysSpikeReg_fwhm-5_atlas-brainnetome_sfc.pscalar.nii', 'results/HCP/sub-HCD0534138/func/sub-HCD0534138_task-rest_den-91k_desc-preproc_denoise-24HMP8PhysSpikeReg_fwhm-5_atlas-brainnetome_sfc.pscalar.nii', 'results/HCP/sub-HCD0536142/func/sub-HCD0536142_task-rest_den-91k_desc-preproc_denoise-24HMP8PhysSpikeReg_fwhm-5_atlas-brainnetome_sfc.pscalar.nii', 'results/HCP/sub-HCD0541539/func/sub-HCD0541539_task-rest_den-91k_desc-preproc_denoise-24HMP8PhysSpikeReg_fwhm-5_atlas-brainnetome_sfc.pscalar.nii', 'results/HCP/sub-HCD0551946/func/sub-HCD0551946_task-rest_den-91k_desc-preproc_denoise-24HMP8PhysSpikeReg_fwhm-5_atlas-brainnetome_sfc.pscalar.nii', 'results/HCP/sub-HCD0555146/func/sub-HCD0555146_task-rest_den-91k_desc-preproc_denoise-24HMP8PhysSpikeReg_fwhm-5_atlas-brainnetome_sfc.pscalar.nii', 'results/HCP/sub-HCD0576558/func/sub-HCD0576558_task-rest_den-91k_desc-preproc_denoise-24HMP8PhysSpikeReg_fwhm-5_atlas-brainnetome_sfc.pscalar.nii', 'results/HCP/sub-HCD0577661/func/sub-HCD0577661_task-rest_den-91k_desc-preproc_denoise-24HMP8PhysSpikeReg_fwhm-5_atlas-brainnetome_sfc.pscalar.nii', 'results/HCP/sub-HCD0583555/func/sub-HCD0583555_task-rest_den-91k_desc-preproc_denoise-24HMP8PhysSpikeReg_fwhm-5_atlas-brainnetome_sfc.pscalar.nii', 'results/HCP/sub-HCD0605135/func/sub-HCD0605135_task-rest_den-91k_desc-preproc_denoise-24HMP8PhysSpikeReg_fwhm-5_atlas-brainnetome_sfc.pscalar.nii', 'results/HCP/sub-HCD0605438/func/sub-HCD0605438_task-rest_den-91k_desc-preproc_denoise-24HMP8PhysSpikeReg_fwhm-5_atlas-brainnetome_sfc.pscalar.nii', 'results/HCP/sub-HCD0616342/func/sub-HCD0616342_task-rest_den-91k_desc-preproc_denoise-24HMP8PhysSpikeReg_fwhm-5_atlas-brainnetome_sfc.pscalar.nii', 'results/HCP/sub-HCD0621638/func/sub-HCD0621638_task-rest_den-91k_desc-preproc_denoise-24HMP8PhysSpikeReg_fwhm-5_atlas-brainnetome_sfc.pscalar.nii', 'results/HCP/sub-HCD0641341/func/sub-HCD0641341_task-rest_den-91k_desc-preproc_denoise-24HMP8PhysSpikeReg_fwhm-5_atlas-brainnetome_sfc.pscalar.nii', 'results/HCP/sub-HCD0643345/func/sub-HCD0643345_task-rest_den-91k_desc-preproc_denoise-24HMP8PhysSpikeReg_fwhm-5_atlas-brainnetome_sfc.pscalar.nii', 'results/HCP/sub-HCD0644044/func/sub-HCD0644044_task-rest_den-91k_desc-preproc_denoise-24HMP8PhysSpikeReg_fwhm-5_atlas-brainnetome_sfc.pscalar.nii', 'results/HCP/sub-HCD0664656/func/sub-HCD0664656_task-rest_den-91k_desc-preproc_denoise-24HMP8PhysSpikeReg_fwhm-5_atlas-brainnetome_sfc.pscalar.nii', 'results/HCP/sub-HCD0667763/func/sub-HCD0667763_task-rest_den-91k_desc-preproc_denoise-24HMP8PhysSpikeReg_fwhm-5_atlas-brainnetome_sfc.pscalar.nii', 'results/HCP/sub-HCD0678970/func/sub-HCD0678970_task-rest_den-91k_desc-preproc_denoise-24HMP8PhysSpikeReg_fwhm-5_atlas-brainnetome_sfc.pscalar.nii', 'results/HCP/sub-HCD0682557/func/sub-HCD0682557_task-rest_den-91k_desc-preproc_denoise-24HMP8PhysSpikeReg_fwhm-5_atlas-brainnetome_sfc.pscalar.nii', 'results/HCP/sub-HCD0684460/func/sub-HCD0684460_task-rest_den-91k_desc-preproc_denoise-24HMP8PhysSpikeReg_fwhm-5_atlas-brainnetome_sfc.pscalar.nii', 'results/HCP/sub-HCD0686666/func/sub-HCD0686666_task-rest_den-91k_desc-preproc_denoise-24HMP8PhysSpikeReg_fwhm-5_atlas-brainnetome_sfc.pscalar.nii', 'results/HCP/sub-HCD0703943/func/sub-HCD0703943_task-rest_den-91k_desc-preproc_denoise-24HMP8PhysSpikeReg_fwhm-5_atlas-brainnetome_sfc.pscalar.nii', 'results/HCP/sub-HCD0758867/func/sub-HCD0758867_task-rest_den-91k_desc-preproc_denoise-24HMP8PhysSpikeReg_fwhm-5_atlas-brainnetome_sfc.pscalar.nii', 'results/HCP/sub-HCD0777265/func/sub-HCD0777265_task-rest_den-91k_desc-preproc_denoise-24HMP8PhysSpikeReg_fwhm-5_atlas-brainnetome_sfc.pscalar.nii', 'results/HCP/sub-HCD0784060/func/sub-HCD0784060_task-rest_den-91k_desc-preproc_denoise-24HMP8PhysSpikeReg_fwhm-5_atlas-brainnetome_sfc.pscalar.nii', 'results/HCP/sub-HCD0789272/func/sub-HCD0789272_task-rest_den-91k_desc-preproc_denoise-24HMP8PhysSpikeReg_fwhm-5_atlas-brainnetome_sfc.pscalar.nii', 'results/HCP/sub-HCD0796067/func/sub-HCD0796067_task-rest_den-91k_desc-preproc_denoise-24HMP8PhysSpikeReg_fwhm-5_atlas-brainnetome_sfc.pscalar.nii', 'results/HCP/sub-HCD0797877/func/sub-HCD0797877_task-rest_den-91k_desc-preproc_denoise-24HMP8PhysSpikeReg_fwhm-5_atlas-brainnetome_sfc.pscalar.nii', 'results/HCP/sub-HCD0802440/func/sub-HCD0802440_task-rest_den-91k_desc-preproc_denoise-24HMP8PhysSpikeReg_fwhm-5_atlas-brainnetome_sfc.pscalar.nii', 'results/HCP/sub-HCD0804545/func/sub-HCD0804545_task-rest_den-91k_desc-preproc_denoise-24HMP8PhysSpikeReg_fwhm-5_atlas-brainnetome_sfc.pscalar.nii', 'results/HCP/sub-HCD0808654/func/sub-HCD0808654_task-rest_den-91k_desc-preproc_denoise-24HMP8PhysSpikeReg_fwhm-5_atlas-brainnetome_sfc.pscalar.nii', 'results/HCP/sub-HCD0810035/func/sub-HCD0810035_task-rest_den-91k_desc-preproc_denoise-24HMP8PhysSpikeReg_fwhm-5_atlas-brainnetome_sfc.pscalar.nii', 'results/HCP/sub-HCD0812241/func/sub-HCD0812241_task-rest_den-91k_desc-preproc_denoise-24HMP8PhysSpikeReg_fwhm-5_atlas-brainnetome_sfc.pscalar.nii', 'results/HCP/sub-HCD0822850/func/sub-HCD0822850_task-rest_den-91k_desc-preproc_denoise-24HMP8PhysSpikeReg_fwhm-5_atlas-brainnetome_sfc.pscalar.nii', 'results/HCP/sub-HCD0842250/func/sub-HCD0842250_task-rest_den-91k_desc-preproc_denoise-24HMP8PhysSpikeReg_fwhm-5_atlas-brainnetome_sfc.pscalar.nii', 'results/HCP/sub-HCD0845458/func/sub-HCD0845458_task-rest_den-91k_desc-preproc_denoise-24HMP8PhysSpikeReg_fwhm-5_atlas-brainnetome_sfc.pscalar.nii', 'results/HCP/sub-HCD0848060/func/sub-HCD0848060_task-rest_den-91k_desc-preproc_denoise-24HMP8PhysSpikeReg_fwhm-5_atlas-brainnetome_sfc.pscalar.nii', 'results/HCP/sub-HCD0857566/func/sub-HCD0857566_task-rest_den-91k_desc-preproc_denoise-24HMP8PhysSpikeReg_fwhm-5_atlas-brainnetome_sfc.pscalar.nii', 'results/HCP/sub-HCD0858467/func/sub-HCD0858467_task-rest_den-91k_desc-preproc_denoise-24HMP8PhysSpikeReg_fwhm-5_atlas-brainnetome_sfc.pscalar.nii', 'results/HCP/sub-HCD0869371/func/sub-HCD0869371_task-rest_den-91k_desc-preproc_denoise-24HMP8PhysSpikeReg_fwhm-5_atlas-brainnetome_sfc.pscalar.nii', 'results/HCP/sub-HCD0891566/func/sub-HCD0891566_task-rest_den-91k_desc-preproc_denoise-24HMP8PhysSpikeReg_fwhm-5_atlas-brainnetome_sfc.pscalar.nii', 'results/HCP/sub-HCD0894875/func/sub-HCD0894875_task-rest_den-91k_desc-preproc_denoise-24HMP8PhysSpikeReg_fwhm-5_atlas-brainnetome_sfc.pscalar.nii', 'results/HCP/sub-HCD0904650/func/sub-HCD0904650_task-rest_den-91k_desc-preproc_denoise-24HMP8PhysSpikeReg_fwhm-5_atlas-brainnetome_sfc.pscalar.nii', 'results/HCP/sub-HCD0921145/func/sub-HCD0921145_task-rest_den-91k_desc-preproc_denoise-24HMP8PhysSpikeReg_fwhm-5_atlas-brainnetome_sfc.pscalar.nii', 'results/HCP/sub-HCD0925759/func/sub-HCD0925759_task-rest_den-91k_desc-preproc_denoise-24HMP8PhysSpikeReg_fwhm-5_atlas-brainnetome_sfc.pscalar.nii', 'results/HCP/sub-HCD0933051/func/sub-HCD0933051_task-rest_den-91k_desc-preproc_denoise-24HMP8PhysSpikeReg_fwhm-5_atlas-brainnetome_sfc.pscalar.nii', 'results/HCP/sub-HCD0946868/func/sub-HCD0946868_task-rest_den-91k_desc-preproc_denoise-24HMP8PhysSpikeReg_fwhm-5_atlas-brainnetome_sfc.pscalar.nii', 'results/HCP/sub-HCD0956871/func/sub-HCD0956871_task-rest_den-91k_desc-preproc_denoise-24HMP8PhysSpikeReg_fwhm-5_atlas-brainnetome_sfc.pscalar.nii', 'results/HCP/sub-HCD0969072/func/sub-HCD0969072_task-rest_den-91k_desc-preproc_denoise-24HMP8PhysSpikeReg_fwhm-5_atlas-brainnetome_sfc.pscalar.nii', 'results/HCP/sub-HCD0977576/func/sub-HCD0977576_task-rest_den-91k_desc-preproc_denoise-24HMP8PhysSpikeReg_fwhm-5_atlas-brainnetome_sfc.pscalar.nii', 'results/HCP/sub-HCD0979378/func/sub-HCD0979378_task-rest_den-91k_desc-preproc_denoise-24HMP8PhysSpikeReg_fwhm-5_atlas-brainnetome_sfc.pscalar.nii', 'results/HCP/sub-HCD0988682/func/sub-HCD0988682_task-rest_den-91k_desc-preproc_denoise-24HMP8PhysSpikeReg_fwhm-5_atlas-brainnetome_sfc.pscalar.nii', 'results/HCP/sub-HCD0997380/func/sub-HCD0997380_task-rest_den-91k_desc-preproc_denoise-24HMP8PhysSpikeReg_fwhm-5_atlas-brainnetome_sfc.pscalar.nii', 'results/HCP/sub-HCD1003617/func/sub-HCD1003617_task-rest_den-91k_desc-preproc_denoise-24HMP8PhysSpikeReg_fwhm-5_atlas-brainnetome_sfc.pscalar.nii', 'results/HCP/sub-HCD1007423/func/sub-HCD1007423_task-rest_den-91k_desc-preproc_denoise-24HMP8PhysSpikeReg_fwhm-5_atlas-brainnetome_sfc.pscalar.nii', 'results/HCP/sub-HCD1010311/func/sub-HCD1010311_task-rest_den-91k_desc-preproc_denoise-24HMP8PhysSpikeReg_fwhm-5_atlas-brainnetome_sfc.pscalar.nii', 'results/HCP/sub-HCD1010412/func/sub-HCD1010412_task-rest_den-91k_desc-preproc_denoise-24HMP8PhysSpikeReg_fwhm-5_atlas-brainnetome_sfc.pscalar.nii', 'results/HCP/sub-HCD1017729/func/sub-HCD1017729_task-rest_den-91k_desc-preproc_denoise-24HMP8PhysSpikeReg_fwhm-5_atlas-brainnetome_sfc.pscalar.nii', 'results/HCP/sub-HCD1017931/func/sub-HCD1017931_task-rest_den-91k_desc-preproc_denoise-24HMP8PhysSpikeReg_fwhm-5_atlas-brainnetome_sfc.pscalar.nii', 'results/HCP/sub-HCD1022722/func/sub-HCD1022722_task-rest_den-91k_desc-preproc_denoise-24HMP8PhysSpikeReg_fwhm-5_atlas-brainnetome_sfc.pscalar.nii', 'results/HCP/sub-HCD1029837/func/sub-HCD1029837_task-rest_den-91k_desc-preproc_denoise-24HMP8PhysSpikeReg_fwhm-5_atlas-brainnetome_sfc.pscalar.nii', 'results/HCP/sub-HCD1039032/func/sub-HCD1039032_task-rest_den-91k_desc-preproc_denoise-24HMP8PhysSpikeReg_fwhm-5_atlas-brainnetome_sfc.pscalar.nii', 'results/HCP/sub-HCD1093139/func/sub-HCD1093139_task-rest_den-91k_desc-preproc_denoise-24HMP8PhysSpikeReg_fwhm-5_atlas-brainnetome_sfc.pscalar.nii', 'results/HCP/sub-HCD1103419/func/sub-HCD1103419_task-rest_den-91k_desc-preproc_denoise-24HMP8PhysSpikeReg_fwhm-5_atlas-brainnetome_sfc.pscalar.nii', 'results/HCP/sub-HCD1106728/func/sub-HCD1106728_task-rest_den-91k_desc-preproc_denoise-24HMP8PhysSpikeReg_fwhm-5_atlas-brainnetome_sfc.pscalar.nii', 'results/HCP/sub-HCD1108833/func/sub-HCD1108833_task-rest_den-91k_desc-preproc_denoise-24HMP8PhysSpikeReg_fwhm-5_atlas-brainnetome_sfc.pscalar.nii', 'results/HCP/sub-HCD1111822/func/sub-HCD1111822_task-rest_den-91k_desc-preproc_denoise-24HMP8PhysSpikeReg_fwhm-5_atlas-brainnetome_sfc.pscalar.nii', 'results/HCP/sub-HCD11132

In [7]:
#from snakebids.utils.snakemake_io import glob_wildcards
#subjects = glob_wildcards(sfc_pattern.format(dataset='HCP',subject='{subject}'))

if 'LOBE' in sfc_paths:
    print(f"Number of files in sfc_paths['LOBE']: {len(sfc_paths['LOBE'])}")
else:
    print("'LOBE' key is not in sfc_paths.")

Number of files in sfc_paths['LOBE']: 27

In [8]:
sfc={}
fc={}
sc={}
num_parcels = nib.load(sfc_paths['LOBE'][0]).get_fdata().shape[1]
datasets=['HCP','LOBE']
for dataset in datasets:
    sfc[dataset] = np.concatenate(  [ nib.load(path).get_fdata()  for path in sfc_paths[dataset]] ,axis=0)
    fc[dataset] = np.concatenate(  [ nib.load(path).get_fdata().reshape((1,num_parcels,num_parcels))  for path in fc_paths[dataset]] ,axis=0)
    sc[dataset] = np.concatenate(  [ nib.load(path).get_fdata().reshape((1,num_parcels,num_parcels))  for path in sc_paths[dataset]] ,axis=0)

In [16]:
print(sfc)

{'HCP': array([[ 0.32635603,  0.28220234, -0.16009923, ...,  0.06199732,
         0.08279282,  0.10664156],
       [ 0.42717829,  0.36375681,  0.34887707, ..., -0.04169991,
         0.15109274, -0.13557212],
       [ 0.21538745,  0.48634909, -0.03678593, ...,  0.00475206,
         0.15430157,  0.16919284],
       ...,
       [ 0.33807884,  0.20825125, -0.02771243, ..., -0.03266236,
         0.30489908,  0.04592518],
       [ 0.29703797,  0.32281828,  0.15757893, ...,  0.00749867,
         0.11550925,  0.22265269],
       [ 0.11709499,  0.15249242, -0.04420549, ...,  0.08199653,
         0.16516709,  0.17526528]], shape=(341, 246)), 'LOBE': array([[ 0.13582964,  0.22719569,  0.22572904, ...,  0.14024365,
         0.25564845,  0.131271  ],
       [ 0.14890697,  0.21303181,  0.22511186, ..., -0.00227409,
         0.1022239 , -0.1462879 ],
       [ 0.18902272,  0.24449654, -0.11343633, ...,  0.11724435,
         0.13878247,  0.18274519],
       ...,
       [ 0.34007227,  0.32345104,  0.14331519, ...,  0.03100847,
         0.28417737,  0.04369498],
       [        nan,         nan,         nan, ...,         nan,
                nan,         nan],
       [        nan,         nan,         nan, ...,         nan,
                nan,         nan]], shape=(27, 246))}

In [9]:
print(df_tabular)

     participant_id dataset        age sex  age_seizure_onset  \
0    sub-HCD0001305     HCP  11.916667   M                NaN
1    sub-HCD0021614     HCP   9.166667   F                NaN
2    sub-HCD0026119     HCP  15.166667   F                NaN
3    sub-HCD0041822     HCP  17.416667   M                NaN
4    sub-HCD0042420     HCP  18.333333   M                NaN
..              ...     ...        ...  ..                ...
363         sub-035    LOBE   7.000000   M                2.0
364         sub-036    LOBE  15.000000   M               10.0
365         sub-038    LOBE  10.000000   F                7.0
366         sub-040    LOBE   9.000000   F                5.0
367         sub-041    LOBE  12.000000   M                4.0

     age_ep_diagnosis  ep_duration_first_scan  seizure_duration_first_scan  \
0                 NaN                     NaN                          NaN
1                 NaN                     NaN                          NaN
2                 NaN                     NaN                          NaN
3                 NaN                     NaN                          NaN
4                 NaN                     NaN                          NaN
..                ...                     ...                          ...
363               4.0                     3.0                          5.0
364               NaN                     NaN                          5.0
365               7.0                     3.0                          3.0
366               NaN                     NaN                          4.0
367               NaN                     NaN                          8.0

     pnes  benign_rolandic  ... loc_pet_occipital  loc_pet_parietal  \
0     NaN              NaN  ...               NaN               NaN
1     NaN              NaN  ...               NaN               NaN
2     NaN              NaN  ...               NaN               NaN
3     NaN              NaN  ...               NaN               NaN
4     NaN              NaN  ...               NaN               NaN
..    ...              ...  ...               ...               ...
363   0.0              0.0  ...               NaN               NaN
364   NaN              NaN  ...               NaN               NaN
365   0.0              0.0  ...               NaN               NaN
366   NaN              NaN  ...               NaN               NaN
367   NaN              NaN  ...               NaN               NaN

     loc_pet_temporal  loc_semiology  loc_final_frontal  loc_final_occipital  \
0                 NaN            NaN                NaN                  NaN
1                 NaN            NaN                NaN                  NaN
2                 NaN            NaN                NaN                  NaN
3                 NaN            NaN                NaN                  NaN
4                 NaN            NaN                NaN                  NaN
..                ...            ...                ...                  ...
363               NaN            NaN                  1                    0
364               NaN            NaN                NaN                  NaN
365               NaN       parietal                  0                    0
366               NaN            NaN            unknown              unknown
367               NaN            NaN                NaN                  NaN

     loc_final_parietal  loc_final_temporal  loc_final_temporal_plus  \
0                   NaN                 NaN                      NaN
1                   NaN                 NaN                      NaN
2                   NaN                 NaN                      NaN
3                   NaN                 NaN                      NaN
4                   NaN                 NaN                      NaN
..                  ...                 ...                      ...
363                   0                   0                      0.0
364                 NaN                 NaN                      NaN
365                   1                   0                      0.0
366             unknown             unknown                      NaN
367                 NaN                   1                      NaN

     loc_final_extratemporal
0                        NaN
1                        NaN
2                        NaN
3                        NaN
4                        NaN
..                       ...
363                      0.0
364                      NaN
365                      0.0
366                      NaN
367                      NaN

[368 rows x 57 columns]

In [9]:

#this adds RSFC features as new columns to the df_tabular

df_list=[]
for dataset in datasets:
    df_=pd.DataFrame(sfc[dataset],
                 columns=('RSFC_'+df_labels.name))
    
    df_tabular_ = df_tabular.query(f"dataset == '{dataset}'")
    #df_['participant_id'] = snakemake.params.subjects[dataset]

    # Check that the number of rows in df_ matches the number of subjects
    #participant_ids = subjects[dataset]
    
    # Assign participant IDs directly to df_
    #df_['participant_id'] = participant_ids
    df_['participant_id'] = ['sub-'+subject for subject in subjects[dataset]]
    df_merged_ = pd.merge(df_tabular_,df_,how='left',on='participant_id')
    df_list.append(df_merged_)

df_tabular = pd.concat(df_list)

In [11]:
print(df_tabular)

    participant_id dataset        age sex  age_seizure_onset  \
0   sub-HCD0001305     HCP  11.916667   M                NaN
1   sub-HCD0021614     HCP   9.166667   F                NaN
2   sub-HCD0026119     HCP  15.166667   F                NaN
3   sub-HCD0041822     HCP  17.416667   M                NaN
4   sub-HCD0042420     HCP  18.333333   M                NaN
..             ...     ...        ...  ..                ...
22         sub-035    LOBE   7.000000   M                2.0
23         sub-036    LOBE  15.000000   M               10.0
24         sub-038    LOBE  10.000000   F                7.0
25         sub-040    LOBE   9.000000   F                5.0
26         sub-041    LOBE  12.000000   M                4.0

    age_ep_diagnosis  ep_duration_first_scan  seizure_duration_first_scan  \
0                NaN                     NaN                          NaN
1                NaN                     NaN                          NaN
2                NaN                     NaN                          NaN
3                NaN                     NaN                          NaN
4                NaN                     NaN                          NaN
..               ...                     ...                          ...
22               4.0                     3.0                          5.0
23               NaN                     NaN                          5.0
24               7.0                     3.0                          3.0
25               NaN                     NaN                          4.0
26               NaN                     NaN                          8.0

    pnes  benign_rolandic  ... RSFC_L_rTtha_Subcort  RSFC_R_rTtha_Subcort  \
0    NaN              NaN  ...             0.145824              0.016409
1    NaN              NaN  ...             0.098973             -0.217379
2    NaN              NaN  ...             0.111897              0.080966
3    NaN              NaN  ...            -0.186074              0.137191
4    NaN              NaN  ...            -0.128780             -0.028401
..   ...              ...  ...                  ...                   ...
22   0.0              0.0  ...            -0.069272              0.117659
23   NaN              NaN  ...                  NaN                   NaN
24   0.0              0.0  ...             0.024724              0.196889
25   NaN              NaN  ...                  NaN                   NaN
26   NaN              NaN  ...                  NaN                   NaN

    RSFC_L_PPtha_Subcort  RSFC_R_PPtha_Subcort  RSFC_L_Otha_Subcort  \
0              -0.061787              0.189184             0.020822
1               0.085291             -0.131448             0.091554
2               0.119486             -0.006838             0.130075
3              -0.051728              0.121819             0.021278
4               0.218825              0.083926             0.076028
..                   ...                   ...                  ...
22              0.110069              0.234485             0.098933
23                   NaN                   NaN                  NaN
24              0.037722              0.041491             0.093532
25                   NaN                   NaN                  NaN
26                   NaN                   NaN                  NaN

    RSFC_R_Otha_Subcort  RSFC_L_cTtha_Subcort  RSFC_R_cTtha_Subcort  \
0              0.177150              0.064210              0.061997
1              0.055287              0.134133             -0.041700
2              0.164142              0.123662              0.004752
3              0.271471              0.016295              0.012345
4             -0.020074             -0.000332              0.014403
..                  ...                   ...                   ...
22             0.089826              0.133242             -0.081011
23                  NaN                   NaN                   NaN
24             0.185894             -0.011517              0.031008
25                  NaN                   NaN                   NaN
26                  NaN                   NaN                   NaN

    RSFC_L_lPFtha_Subcort  RSFC_R_lPFtha_Subcort
0                0.082793               0.106642
1                0.151093              -0.135572
2                0.154302               0.169193
3                0.167308               0.036582
4                0.176461               0.179572
..                    ...                    ...
22               0.171381              -0.245164
23                    NaN                    NaN
24               0.284177               0.043695
25                    NaN                    NaN
26                    NaN                    NaN

[368 rows x 303 columns]

In [10]:
print(f"Length of sfc[dataset] for 'LOBE': {len(sfc[dataset])}")

Length of sfc[dataset] for 'LOBE': 27

## Average FC per parcel ##

In [11]:
#set diagonal to be nan
x1 = fc['HCP']
for s in range(x1.shape[0]):
    conn = x1[s,:,:]    
    mask = np.eye(num_parcels)
    conn[mask==1] = np.nan
    x1[s,:,:] = conn

x2 = fc['LOBE']
for s in range(x2.shape[0]):
    conn = x2[s,:,:]
    mask = np.eye(num_parcels)
    conn[mask==1] = np.nan
    x2[s,:,:] = conn

In [12]:
x2.shape

(27, 246, 246)

In [13]:
x1 = np.nanmean(x1,axis=2)
x2 = np.nanmean(x2,axis=2)

/tmp/ipykernel_169869/3377732870.py:2: RuntimeWarning: Mean of empty slice
  x2 = np.nanmean(x2,axis=2)

In [14]:
x1.shape

(341, 246)

In [15]:
x2.shape

(27, 246)

In [16]:
#add FC parcel avgs to tabular df

data_={'HCP':x1,'LOBE':x2}

df_list=[]
for dataset in datasets:

    
    df_=pd.DataFrame(data_[dataset],
                 columns=('RFC_'+df_labels.name))
    
    df_tabular_ = df_tabular.query(f"dataset == '{dataset}'")
   # df_['participant_id'] = snakemake.params.subjects[dataset]
    #participant_ids = subjects[dataset]
    #df_['participant_id'] = participant_ids
    df_['participant_id'] = ['sub-'+subject for subject in subjects[dataset]]
    
    df_merged_ = pd.merge(df_tabular_,df_,how='left',on='participant_id')
    df_list.append(df_merged_)

df_tabular = pd.concat(df_list)

In [17]:
print(df_tabular)

    participant_id dataset        age sex  age_seizure_onset  \
0   sub-HCD0001305     HCP  11.916667   M                NaN
1   sub-HCD0021614     HCP   9.166667   F                NaN
2   sub-HCD0026119     HCP  15.166667   F                NaN
3   sub-HCD0041822     HCP  17.416667   M                NaN
4   sub-HCD0042420     HCP  18.333333   M                NaN
..             ...     ...        ...  ..                ...
22         sub-035    LOBE   7.000000   M                2.0
23         sub-036    LOBE  15.000000   M               10.0
24         sub-038    LOBE  10.000000   F                7.0
25         sub-040    LOBE   9.000000   F                5.0
26         sub-041    LOBE  12.000000   M                4.0

    age_ep_diagnosis  ep_duration_first_scan  seizure_duration_first_scan  \
0                NaN                     NaN                          NaN
1                NaN                     NaN                          NaN
2                NaN                     NaN                          NaN
3                NaN                     NaN                          NaN
4                NaN                     NaN                          NaN
..               ...                     ...                          ...
22               4.0                     3.0                          5.0
23               NaN                     NaN                          5.0
24               7.0                     3.0                          3.0
25               NaN                     NaN                          4.0
26               NaN                     NaN                          8.0

    pnes  benign_rolandic  ... RFC_L_rTtha_Subcort  RFC_R_rTtha_Subcort  \
0    NaN              NaN  ...            0.121187             0.074785
1    NaN              NaN  ...            0.101887             0.231632
2    NaN              NaN  ...            0.035121             0.075685
3    NaN              NaN  ...            0.158135             0.114994
4    NaN              NaN  ...            0.272021             0.269457
..   ...              ...  ...                 ...                  ...
22   0.0              0.0  ...           -0.061666            -0.020366
23   NaN              NaN  ...            0.031229             0.062531
24   0.0              0.0  ...            0.258884             0.031030
25   NaN              NaN  ...            0.032103             0.286835
26   NaN              NaN  ...            0.154628             0.097381

    RFC_L_PPtha_Subcort  RFC_R_PPtha_Subcort  RFC_L_Otha_Subcort  \
0              0.254910             0.235497            0.199661
1              0.341675             0.248012            0.189673
2              0.202221             0.060381            0.238343
3              0.126322             0.169497            0.134374
4              0.176352             0.231813            0.198918
..                  ...                  ...                 ...
22             0.069726             0.071347            0.064541
23             0.118312             0.104038            0.034288
24             0.250400             0.174593            0.225283
25             0.108799             0.142716           -0.092051
26             0.219349             0.220229            0.190482

    RFC_R_Otha_Subcort  RFC_L_cTtha_Subcort  RFC_R_cTtha_Subcort  \
0             0.232484             0.261365             0.066489
1             0.011641             0.175432             0.150430
2            -0.059527             0.023376            -0.033248
3             0.127568             0.133300             0.140944
4             0.222668             0.268511             0.169719
..                 ...                  ...                  ...
22            0.057865            -0.012988             0.014238
23            0.121742             0.094189             0.130274
24           -0.026058             0.278105             0.230352
25            0.249828             0.123224             0.285501
26            0.173441             0.140239             0.203556

    RFC_L_lPFtha_Subcort  RFC_R_lPFtha_Subcort
0               0.301524              0.286051
1               0.341565              0.287935
2               0.161414              0.122034
3               0.098755              0.153137
4               0.001470              0.175611
..                   ...                   ...
22             -0.070302              0.024922
23              0.080915              0.130825
24              0.145438              0.164439
25              0.171219              0.156044
26              0.176804              0.311680

[368 rows x 549 columns]

# Structural Connectivity #

## Average SC per parcel ##

In [18]:
#set diagonal to be nan
x1 = sc['HCP']
for s in range(x1.shape[0]):
    conn = x1[s,:,:]    
    mask = np.eye(num_parcels)
    conn[mask==1] = np.nan
    x1[s,:,:] = conn

x2 = sc['LOBE']
for s in range(x2.shape[0]):
    conn = x2[s,:,:]
    mask = np.eye(num_parcels)
    conn[mask==1] = np.nan
    x2[s,:,:] = conn

In [19]:
x1.shape

(341, 246, 246)

In [20]:
x1 = np.nanmean(x1,axis=2)
x1.shape
x2 = np.nanmean(x2,axis=2)
x2.shape

(27, 246)

In [21]:
x1.shape

(341, 246)

In [22]:
x2.shape

(27, 246)

In [23]:
#add SC parcel avgs to tabular df

data_={'HCP':x1,'LOBE':x2}

df_list=[]
for dataset in datasets:

    
    df_=pd.DataFrame(data_[dataset],
                 columns=('RSC_'+df_labels.name))
    
    df_tabular_ = df_tabular.query(f"dataset == '{dataset}'")
    #df_['participant_id'] = snakemake.params.subjects[dataset]
    #participant_ids = subjects[dataset]
    #df_['participant_id'] = participant_ids
    df_['participant_id'] = ['sub-'+subject for subject in subjects[dataset]]
    df_merged_ = pd.merge(df_tabular_,df_,how='left',on='participant_id')
    df_list.append(df_merged_)

df_tabular = pd.concat(df_list)

# Network-Wise, LOBE vs HCP #

## Paths ##

In [31]:
# Brainnetome Patterns
fc_network_pattern='results/{dataset}/sub-{subject}/func/sub-{subject}_task-rest_den-91k_desc-preproc_denoise-24HMP8PhysSpikeReg_fwhm-5_atlas-brainnetome_netbold.pconn.nii'
sc_network_pattern='results/{dataset}/sub-{subject}/dwi/sub-{subject}_den-91k_atlas-brainnetome_netstruc.pconn.nii'
sfc_network_pattern='results/{dataset}/sub-{subject}/func/sub-{subject}_task-rest_den-91k_desc-preproc_denoise-24HMP8PhysSpikeReg_fwhm-5_atlas-brainnetome_netsfc.pconn.nii'

In [32]:

sfc_netpaths={ dataset: sorted([sfc_network_pattern.format(dataset=dataset,subject=subject) for subject in subjects[dataset]]) 
               for dataset in subjects.keys() }

fc_netpaths={ dataset: sorted([fc_network_pattern.format(dataset=dataset,subject=subject) for subject in subjects[dataset]]) 
               for dataset in subjects.keys() }

sc_netpaths={ dataset: sorted([sc_network_pattern.format(dataset=dataset,subject=subject) for subject in subjects[dataset]]) 
               for dataset in subjects.keys() }

In [33]:
sfc={}
fc={}
sc={}
num_parcels = nib.load(sfc_netpaths['LOBE'][0]).get_fdata().shape[1]

for dataset in datasets:

    sfc[dataset] = np.concatenate(  [ nib.load(path).get_fdata().reshape((1,num_parcels,num_parcels))  for path in sfc_netpaths[dataset]] ,axis=0)  
    fc[dataset] = np.concatenate(  [ nib.load(path).get_fdata().reshape((1,num_parcels,num_parcels))  for path in fc_netpaths[dataset]] ,axis=0)
    sc[dataset] = np.concatenate(  [ nib.load(path).get_fdata().reshape((1,num_parcels,num_parcels))  for path in sc_netpaths[dataset]] ,axis=0)

## Within-Network ##

## SFC ##

In [133]:
# # Assuming x1 is of shape (1, 8, 8)
# x1 = sfc['HCP']  # (1, 8, 8)
# num_parcels = x1.shape[1]  # Assuming it's 8

# for s in range(x1.shape[0]):
#     conn = x1[s, :, :]  # Extract the 8x8 matrix for each subject (if there are multiple)
    
#     # Create a mask where only the diagonal elements are True
#      mask = np.eye(num_parcels, dtype=bool)  # A boolean mask with True on the diagonal, False elsewhere
    
#     # Create a copy of the original matrix to avoid modifying the original data directly
#     conn_copy = conn.copy()

#     # Set off-diagonal elements to NaN, but preserve the diagonal
#     conn_copy[~mask] = np.nan  # Set non-diagonal elements to NaN
    
#     x1[s, :, :] = conn_copy  # Update the matrix with the modified values

In [134]:
# # Assuming x2 is of shape (1, 8, 8)
# x2 = sfc['LOBE']  # (1, 8, 8)
# num_parcels = x2.shape[1]  # Assuming it's 8

# for s in range(x2.shape[0]):
#     conn = x2[s, :, :]  # Extract the 8x8 matrix for each subject (if there are multiple)
    
#     # Create a mask where only the diagonal elements are True
#     mask = np.eye(num_parcels, dtype=bool)  # A boolean mask with True on the diagonal, False elsewhere
    
#     # Create a copy of the original matrix to avoid modifying the original data directly
#     conn_copy = conn.copy()

#     # Set off-diagonal elements to NaN, but preserve the diagonal
#     conn_copy[~mask] = np.nan  # Set non-diagonal elements to NaN
    
#     x2[s, :, :] = conn_copy  # Update the matrix with the modified values

In [135]:
# x1 = np.nanmean(x1,axis=2)
# x2 = np.nanmean(x2,axis=2)

### Add to DF - Within-Network SFC ###

In [136]:
# #add SFC network avgs to tabular df

# data_={'HCP':x1,'LOBE':x2}  

# # Example datasets
# datasets = ['LOBE', 'HCP']


# # Assuming df_tabular is already loaded as a DataFrame (replace with your actual file if needed)
# # Example of what df_tabular might look like if it were loaded
# # df_tabular = pd.read_csv("your_file.csv")  # Or however you load df_tabular

# # List to collect merged DataFrames
# df_list = []

# for dataset in datasets:
#     # Create DataFrame for the current dataset
#     df_ = pd.DataFrame(data_[dataset], columns=[f'NSFC_{name}' for name in df_network_names])
    
#     # Filter the main df_tabular by the current dataset
#     df_tabular_ = df_tabular.query(f"dataset == '{dataset}'")
    
#     # Add the participant_ids from the subjects
# #    df_['participant_id'] = subjects[dataset]
#     df_['participant_id'] = snakemake.params.subjects[dataset]

#     # Merge the new df_ with df_tabular_ on 'participant_id'
#     df_merged_ = pd.merge(df_tabular_, df_, how='left', on='participant_id')
    
#     # Append merged DataFrame to the list
#     df_list.append(df_merged_)

# # Concatenate all merged DataFrames
# df_tabular_final = pd.concat(df_list)

# # Display the final DataFrame
# df_tabular_final

## FC ##

In [101]:
# # Assuming x1 is of shape (1, 8, 8)
# x1 = fc['HCP']  # (1, 8, 8)
# num_parcels = x1.shape[1]  # Assuming it's 8

# for s in range(x1.shape[0]):
#     conn = x1[s, :, :]  # Extract the 8x8 matrix for each subject (if there are multiple)
    
#     # Create a mask where only the diagonal elements are True
#     mask = np.eye(num_parcels, dtype=bool)  # A boolean mask with True on the diagonal, False elsewhere
    
#     # Create a copy of the original matrix to avoid modifying the original data directly
#     conn_copy = conn.copy()

#     # Set off-diagonal elements to NaN, but preserve the diagonal
#     conn_copy[~mask] = np.nan  # Set non-diagonal elements to NaN
    
#     x1[s, :, :] = conn_copy  # Update the matrix with the modified values

In [137]:
# # Assuming x2 is of shape (1, 8, 8)
# x2 = fc['LOBE']  # (1, 8, 8)
# num_parcels = x2.shape[1]  # Assuming it's 8

# for s in range(x2.shape[0]):
#     conn = x2[s, :, :]  # Extract the 8x8 matrix for each subject (if there are multiple)
    
#     # Create a mask where only the diagonal elements are True
#     mask = np.eye(num_parcels, dtype=bool)  # A boolean mask with True on the diagonal, False elsewhere
    
#     # Create a copy of the original matrix to avoid modifying the original data directly
#     conn_copy = conn.copy()

#     # Set off-diagonal elements to NaN, but preserve the diagonal
#     conn_copy[~mask] = np.nan  # Set non-diagonal elements to NaN
    
#     x2[s, :, :] = conn_copy  # Update the matrix with the modified values

In [138]:
# x1 = np.nanmean(x1,axis=2)
# x2 = np.nanmean(x2,axis=2)

## Add Within-Network FC to DF ##

In [139]:
# data_={'HCP':x1,'LOBE':x2}  

# # Example datasets
# datasets = ['LOBE', 'HCP']


# # Assuming df_tabular is already loaded as a DataFrame (replace with your actual file if needed)
# # Example of what df_tabular might look like if it were loaded
# # df_tabular = pd.read_csv("your_file.csv")  # Or however you load df_tabular

# # List to collect merged DataFrames
# df_list = []

# for dataset in datasets:
#     # Create DataFrame for the current dataset
#     df_ = pd.DataFrame(data_[dataset], columns=[f'NFC_{name}' for name in df_network_names])
    
#     # Filter the main df_tabular by the current dataset
#     df_tabular_ = df_tabular.query(f"dataset == '{dataset}'")
    
#     # Add the participant_ids from the subjects
#     df_['participant_id'] = snakemake.params.subjects[dataset]
#     #df_['participant_id'] = subjects[dataset]
    
#     # Merge the new df_ with df_tabular_ on 'participant_id'
#     df_merged_ = pd.merge(df_tabular_, df_, how='left', on='participant_id')
    
#     # Append merged DataFrame to the list
#     df_list.append(df_merged_)

# # Concatenate all merged DataFrames
# df_tabular_final = pd.concat(df_list)

# # Display the final DataFrame
# df_tabular_final

# Within-Network SC #

In [140]:
# # Assuming x1 is of shape (1, 8, 8)
# x1 = sc['HCP']  # (1, 8, 8)
# num_parcels = x1.shape[1]  # Assuming it's 8

# for s in range(x1.shape[0]):
#     conn = x1[s, :, :]  # Extract the 8x8 matrix for each subject (if there are multiple)
    
#     # Create a mask where only the diagonal elements are True
#     mask = np.eye(num_parcels, dtype=bool)  # A boolean mask with True on the diagonal, False elsewhere
    
#     # Create a copy of the original matrix to avoid modifying the original data directly
#     conn_copy = conn.copy()

#     # Set off-diagonal elements to NaN, but preserve the diagonal
#     conn_copy[~mask] = np.nan  # Set non-diagonal elements to NaN
    
#     x1[s, :, :] = conn_copy  # Update the matrix with the modified values

In [141]:
# # Assuming x2 is of shape (1, 8, 8)
# x2 = sc['LOBE']  # (1, 8, 8)
# num_parcels = x2.shape[1]  # Assuming it's 8

# for s in range(x2.shape[0]):
#     conn = x2[s, :, :]  # Extract the 8x8 matrix for each subject (if there are multiple)
    
#     # Create a mask where only the diagonal elements are True
#     mask = np.eye(num_parcels, dtype=bool)  # A boolean mask with True on the diagonal, False elsewhere
    
#     # Create a copy of the original matrix to avoid modifying the original data directly
#     conn_copy = conn.copy()

#     # Set off-diagonal elements to NaN, but preserve the diagonal
#     conn_copy[~mask] = np.nan  # Set non-diagonal elements to NaN
    
#     x2[s, :, :] = conn_copy  # Update the matrix with the modified values

In [142]:
 #x1 = np.nanmean(x1,axis=2)
 #x2 = np.nanmean(x2,axis=2)

## Add within-network SC to DF ##

In [143]:
# data_={'HCP':x1,'LOBE':x2}  

# # Example datasets
# datasets = ['LOBE', 'HCP']


# # Assuming df_tabular is already loaded as a DataFrame (replace with your actual file if needed)
# # Example of what df_tabular might look like if it were loaded
# # df_tabular = pd.read_csv("your_file.csv")  # Or however you load df_tabular

# # List to collect merged DataFrames
# df_list = []

# for dataset in datasets:
#     # Create DataFrame for the current dataset
#     df_ = pd.DataFrame(data_[dataset], columns=[f'NSC_{name}' for name in df_network_names])
    
#     # Filter the main df_tabular by the current dataset
#     df_tabular_ = df_tabular.query(f"dataset == '{dataset}'")
    
#     # Add the participant_ids from the subjects
#     df_['participant_id'] = snakemake.params.subjects[dataset]
#     #df_['participant_id'] = subjects[dataset]
    
#     # Merge the new df_ with df_tabular_ on 'participant_id'
#     df_merged_ = pd.merge(df_tabular_, df_, how='left', on='participant_id')
    
#     # Append merged DataFrame to the list
#     df_list.append(df_merged_)

# # Concatenate all merged DataFrames
# df_tabular_final = pd.concat(df_list)

# # Display the final DataFrame
# df_tabular_final

# Network SFC #

In [38]:
# Assuming x2 is of shape (1, 8, 8)

data_={}
for dataset in ['HCP','LOBE']:

    x1 = sfc[dataset]
#    data_[dataset] = np.zeros((x1.shape[0],int((num_parcels*(num_parcels+1))/2)-num_parcels)) #if excluding diagonal
    data_[dataset] = np.zeros((x1.shape[0],int((num_parcels*(num_parcels+1))/2)))
    num_parcels = x1.shape[1]  # Assuming it's 8

    # Loop over each "slice" in x2 (assuming only one slice, so loop over the first element)
    for s in range(x1.shape[0]):
        conn = x1[s, :, :]  # Extract the 8x8 matrix for the current subject        
        # Now loop over the upper triangle to gather values for each "mixture"
        values_subj=[]
        for i in range(num_parcels):
            for j in range(i, num_parcels): # Include diagonal as well by starting at i
                # You are looking at the upper triangular part (i < j)
                # This will collect values from (i, j) where i < j
                #if j>i:
               values_subj.append(conn[i, j])  # Get the value for that specific pair (i, j)
    
        data_[dataset][s,:] = values_subj

In [39]:
print(data_)

{'HCP': array([[ 0.16874974,  0.14881977,  0.08665645, ...,  0.39123207,
         0.23583221,  0.22277174],
       [ 0.20309232,  0.2473086 ,  0.17063164, ...,  0.29998751,
        -0.02494003,  0.15255934],
       [ 0.31746087,  0.2794096 ,  0.15888203, ...,  0.28465004,
         0.07802159,  0.25196312],
       ...,
       [ 0.29287402,  0.284727  ,  0.19474456, ...,  0.5389686 ,
        -0.00125039,  0.25676861],
       [ 0.23152062,  0.15761529,  0.30029363, ...,  0.49821319,
         0.08561865,  0.30086019],
       [ 0.08987293,  0.20699771,  0.16256888, ...,  0.44240857,
         0.0741008 ,  0.26764948]], shape=(341, 36)), 'LOBE': array([[ 2.69849867e-01,  3.01282678e-01,  2.13850549e-01,
         8.15012982e-03,  1.97002822e-01,  1.31269701e-01,
        -9.95035054e-02,  1.29539677e-01,  3.78724650e-01,
         1.15908843e-01,  9.61000973e-02,  1.63632708e-01,
         2.00086443e-01, -2.02527672e-02,  8.75759273e-02,
         1.55644084e-01,  9.37233628e-02,  1.65269468e-01,
         8.66436465e-02,  2.02345826e-01,  1.72422881e-02,
         4.55314240e-01,  1.35379098e-01,  5.47789190e-02,
         1.48605686e-01,  6.95869348e-02,  5.86852338e-02,
         8.55637230e-02,  4.16063802e-03,  7.00129601e-02,
         2.07447936e-01,  3.72624753e-02,  5.52128467e-02,
         2.40467435e-01, -8.90528718e-02,  2.62327004e-01],
       [ 5.36895560e-02, -3.09212531e-02,  1.89746945e-01,
         2.29882270e-02,  1.28949211e-01,  1.14768045e-01,
         1.20712947e-01,  5.61104194e-02,  1.02971905e-01,
         2.91065325e-02,  6.67232396e-03,  6.64615513e-02,
         2.09481680e-01,  9.47874886e-02,  1.10080382e-01,
         1.76457099e-01,  9.65920797e-02,  1.38836701e-01,
         1.35012833e-01,  7.95116390e-02, -2.50584991e-02,
         1.44524828e-01,  1.37096413e-01,  1.40563263e-01,
         5.57502907e-02, -3.33005314e-02,  1.84418850e-01,
         1.37775425e-01,  2.28773557e-02,  2.54418532e-02,
         2.91966534e-01,  1.13924497e-01,  2.33347663e-01,
         2.24826066e-01, -6.51658887e-02,  3.06882902e-01],
       [ 6.29386910e-02,  9.47212378e-02,  1.51430397e-01,
         7.38782215e-02,  1.74092741e-01,  4.83212892e-02,
        -4.00424977e-04, -2.04825553e-02,  2.90049534e-01,
         5.06004270e-02,  1.90610510e-03,  1.29603094e-01,
         1.34575388e-01, -5.66333055e-03, -4.56796022e-02,
         1.94597045e-01,  3.13978378e-01,  2.53792687e-01,
         1.11103745e-01,  2.44557778e-01,  1.40613088e-01,
         3.61400696e-01,  1.26849859e-01,  7.60365149e-02,
         3.37647167e-02, -4.44463703e-02,  3.66820787e-02,
         9.17111466e-02,  1.35192400e-01, -8.44824583e-02,
         6.92378151e-02, -4.04406192e-02,  2.81222645e-02,
         2.31209855e-01,  1.13691623e-01,  5.31464437e-02],
       [ 1.46745988e-01,  2.16486347e-01,  1.79188148e-01,
         3.03272737e-02,  1.66019970e-01,  9.19124408e-02,
         1.01241445e-01,  7.34877815e-02,  3.10782218e-01,
         1.24092955e-01,  6.33815740e-02,  1.16272983e-01,
         1.04236864e-01,  1.75964952e-01, -9.49635202e-03,
         2.35270032e-01,  2.87621450e-01,  3.14129415e-01,
         7.63344380e-03,  1.75491092e-01,  4.72471323e-02,
         3.02930415e-01,  2.20378380e-01, -1.67726900e-02,
         2.50238173e-01, -1.04590973e-02,  1.82250599e-01,
         6.92320973e-03,  8.97152819e-02,  3.23894426e-02,
         1.32535874e-01, -2.28589146e-02, -8.41447988e-03,
         4.31274759e-01,  3.62751010e-02,  5.50539717e-02],
       [ 2.70299611e-01,  1.80351599e-01,  3.03939554e-01,
         9.78265315e-03,  2.65591537e-01,  1.52546842e-01,
         6.50312706e-02,  1.01922047e-01,  2.07127484e-01,
         1.36136239e-01,  3.46211886e-02,  1.64106407e-01,
         2.12620407e-01,  2.20609670e-02,  3.89156252e-02,
         3.49589715e-01,  1.44582703e-01,  1.23579762e-01,
         2.05045301e-01,  1.55214217e-01,  1.25248831e-01,
         5.40796735e-01,  2.37357400e-01,  1.94733779e-01,
         9.81147252e-02, -2.98780007e-02, -3.37499005e-02,
         1.34157010e-01, -9.40596540e-02,  8.70987547e-03,
         3.54777666e-01,  2.59369088e-02,  5.32000649e-02,
         5.24394233e-01, -5.05065989e-02,  1.39704251e-01],
       [ 6.23534979e-02,  1.49224617e-01,  2.03275120e-01,
         7.13244620e-02,  2.84218195e-01,  1.89762752e-01,
         2.39509106e-02, -3.45986328e-03,  2.33459316e-01,
         1.04052140e-01,  8.66867505e-02,  1.79309838e-01,
         2.80384196e-01,  4.28958245e-02, -3.23644477e-02,
         3.02615295e-01,  4.34590247e-02,  2.05518503e-01,
         6.85516644e-02,  2.66507713e-01, -1.03914043e-01,
         3.19003494e-01,  1.65761214e-01,  1.27028050e-01,
         2.26914135e-01,  8.70026966e-02,  1.67075024e-01,
         1.71059685e-01,  3.00077541e-02, -2.58588937e-02,
         2.98874443e-01,  6.20772006e-02,  5.14156715e-02,
         4.69808543e-01, -3.53762739e-02,  2.94866448e-01],
       [ 3.13191631e-01,  1.32478074e-01,  2.52267224e-01,
         1.14019651e-01,  3.26355818e-01,  2.51113675e-02,
         2.25470011e-02,  1.64010188e-01,  2.81269217e-01,
         1.01505506e-01,  6.88948025e-02,  1.41244780e-01,
         1.05418225e-01, -1.69922342e-03,  8.20583026e-02,
         1.96771919e-01,  2.31152536e-01,  2.31926515e-01,
         1.07844425e-01,  1.96416234e-01,  1.64453078e-01,
         3.25711638e-01,  1.21526896e-01,  1.20688469e-01,
         5.36701485e-02,  1.87993129e-02,  8.24640801e-02,
         1.04784151e-01,  8.60438202e-02,  5.60293544e-02,
         1.78534777e-01,  7.81828342e-02,  8.43812570e-02,
         4.28309117e-01, -1.50718926e-01,  3.41787834e-01],
       [ 3.09533063e-01,  3.53941379e-01,  1.58928374e-01,
         9.83162969e-02,  2.18923665e-01,  1.75751562e-01,
         1.12942856e-01,  1.40900857e-01,  3.46877392e-01,
         1.53400020e-01,  1.11614621e-01,  2.18441490e-01,
         2.36029653e-01,  1.33650498e-01,  1.65632804e-01,
         2.53742549e-01,  2.82246193e-01,  2.40369288e-01,
         1.91504252e-01,  2.26958427e-01,  1.50555244e-01,
         5.06333528e-01,  2.29844875e-01,  1.61500819e-01,
         6.00110814e-02,  2.15685864e-01,  2.12531665e-01,
         6.14492363e-02, -3.65268938e-02,  2.00480966e-01,
         2.14456540e-01,  1.03192935e-01,  1.58646406e-01,
         2.70144337e-01, -5.11880980e-02,  1.86074603e-01],
       [ 2.06038683e-01,  1.94493200e-01,  1.23193065e-01,
         6.16417226e-02,  2.10203979e-01,  2.15242180e-02,
        -1.06998387e-02,  1.18468408e-01,  2.09351621e-01,
        -3.41082336e-02,  3.92067705e-02,  1.58911404e-01,
         9.45316403e-02,  1.77533781e-01,  1.60692285e-01,
         2.74939638e-01,  1.94124594e-01,  9.69620741e-02,
        -8.72510109e-03, -8.78341604e-03,  1.21677972e-01,
         1.56865103e-01,  8.48451909e-02,  1.13056929e-01,
         6.34540488e-02,  3.49214163e-02,  7.32919447e-02,
         3.59738014e-02, -5.18849134e-02,  1.53004240e-01,
         6.34951405e-02, -3.64424138e-03,  1.16243170e-02,
         1.78767111e-01, -8.03039034e-03,  1.79562034e-01],
       [ 1.89646501e-01,  2.32544175e-01,  8.04710338e-02,
         7.13438428e-02,  1.32170234e-01,  5.23133621e-03,
         1.52962837e-02,  1.17144151e-01,  2.59953114e-01,
         9.01172786e-02,  1.11644856e-01,  9.00191104e-02,
         1.46547954e-01, -6.42188896e-02,  2.54924531e-02,
         1.77868388e-01,  1.85378762e-01,  2.92555696e-02,
        -2.75454665e-02,  2.90311736e-01,  4.61027410e-02,
         4.23751726e-01,  1.07384445e-01, -7.76748032e-02,
         2.44563754e-01,  5.14990913e-02, -8.91694511e-03,
        -1.13867802e-01,  9.82379734e-02, -1.56424277e-03,
         1.67026918e-01, -1.64503894e-03, -4.89389681e-02,
         5.23601332e-01, -7.00166967e-02,  1.42617695e-01],
       [ 2.66346658e-01,  1.99100377e-01,  2.50402141e-01,
         9.25820130e-02,  2.69940561e-01,  3.96872231e-02,
         2.90500685e-02,  1.50756228e-01,  2.52209358e-01,
         2.41400266e-01,  4.06516420e-02,  1.95109956e-01,
         1.70759446e-01,  3.61243521e-02,  7.26512825e-02,
         3.15735298e-01,  1.78371968e-01,  1.64673140e-01,
         1.42453916e-01,  2.53043265e-01,  4.03084775e-02,
         4.12205131e-01,  1.87473348e-01,  1.36326523e-01,
         1.15299756e-01, -1.04238973e-03,  9.93892160e-02,
        -2.71436935e-02,  2.61106400e-02,  1.25735306e-01,
         1.80965247e-01, -1.57149325e-02,  5.35005987e-02,
         4.06159802e-01, -1.38990857e-01,  1.42099015e-01],
       [ 2.38411777e-01,  2.73268538e-01,  1.70904741e-01,
         5.93121785e-02,  2.60753592e-01,  2.75186271e-02,
         3.51965755e-02,  8.51985453e-02,  3.08691167e-01,
         1.16290797e-01,  5.95131263e-02,  1.96275155e-01,
         2.16764491e-01,  4.29021977e-02, -7.90600397e-02,
         3.28594458e-01,  5.04323653e-03,  8.22030318e-02,
         7.69517310e-02,  9.45620264e-02,  2.02522038e-01,
         4.38915312e-01,  2.11480185e-01,  1.54768818e-01,
         1.00440587e-02,  9.67283061e-04,  1.56600824e-01,
         3.04521423e-02, -2.61122011e-02,  6.25561799e-02,
         1.53484233e-01, -1.04066223e-01,  4.16504110e-02,
         4.72677870e-01, -1.11726779e-02,  2.07377038e-01],
       [ 2.78145524e-01,  8.48521459e-02,  1.51980167e-01,
        -6.74840055e-02,  1.88319137e-01,  4.86920688e-02,
        -3.99908416e-02,  4.26524854e-02,  2.93616123e-01,
        -1.47796085e-02, -5.17094136e-02,  6.75752834e-02,
         1.91001297e-01,  9.04786561e-02, -9.99183173e-02,
         4.23484381e-01,  1.20558094e-01,  3.50300513e-01,
         7.59232380e-02,  3.00123471e-01,  2.17136363e-01,
         3.31735623e-01,  1.58954527e-01,  1.24194362e-01,
         6.04805267e-02,  3.47628521e-02,  7.45237456e-02,
         7.30839936e-02,  3.98473520e-02,  7.95873592e-02,
         7.78967585e-02,  5.47330677e-02,  1.10962215e-01,
         6.12604673e-01,  2.66132068e-02,  2.21578826e-01],
       [ 2.54010862e-01,  2.25971273e-01,  1.94264322e-01,
         8.49122804e-02,  2.47756523e-01,  1.11507302e-01,
        -8.81026261e-02,  1.65668826e-01,  2.64532346e-01,
         2.15616879e-01,  6.18604934e-02,  1.98358105e-01,
         1.29232672e-01,  4.08173321e-02,  9.67103652e-02,
         2.96786062e-01,  1.73018404e-01,  2.87452023e-01,
         1.31952419e-01,  1.44119132e-01,  2.11197302e-01,
         4.25481909e-01,  9.54617779e-02,  1.72790805e-01,
         1.82118481e-01,  1.15551810e-01,  1.71358977e-01,
         1.88051276e-01,  1.64170481e-01,  2.30173181e-01,
         2.04111711e-01,  6.03570543e-02,  1.70775398e-01,
         4.85101556e-01,  2.44781313e-01,  2.97459687e-01],
       [ 8.17764999e-02,  1.09480824e-01,  9.51170450e-02,
        -5.20743405e-03,  7.82996725e-02,  2.02231511e-02,
         8.10039976e-02,  5.10817034e-02,  1.45114331e-01,
         9.11598063e-02, -8.00714148e-02,  9.49044533e-02,
         1.07632742e-01,  5.04346354e-02,  1.00784974e-01,
         6.27347732e-02, -8.22990195e-02,  4.46333914e-02,
         4.69582740e-02,  2.12220539e-01,  1.31392088e-02,
         2.58833265e-02, -4.90682105e-02, -4.16421050e-02,
         5.92701110e-02,  8.41521860e-03,  1.82732661e-01,
         7.70405905e-02, -6.57496337e-03,  1.56382030e-01,
         9.89090877e-03, -4.62613212e-02,  4.40795728e-02,
         2.27950713e-01,  1.10917275e-02,  1.53195431e-01],
       [ 7.08129009e-02,  6.68752294e-02,  3.96691301e-02,
         7.10617035e-02,  1.93218941e-01,  4.19319959e-02,
        -1.08129293e-01, -7.82990885e-03,  3.42204145e-01,
         4.20375337e-02,  1.67262905e-01,  2.25134286e-01,
         2.36846470e-01,  6.72945253e-02,  1.47533292e-01,
         1.87821493e-01,  2.92965205e-01,  1.63074023e-01,
         1.02341002e-01,  2.49617675e-01,  3.23003519e-02,
         4.80548924e-01,  9.22872484e-02,  2.27599285e-01,
         2.19109849e-02, -8.28293739e-02,  1.77896639e-02,
         1.68849241e-01,  1.28941429e-01, -1.08930593e-01,
         2.85342968e-01,  1.24922847e-01,  1.68661969e-01,
         5.04923906e-01, -1.01577709e-03,  1.89109135e-01],
       [ 1.82887450e-01,  2.68746915e-01,  1.84010105e-01,
         8.97228410e-02,  2.28005783e-01,  3.42821569e-02,
         2.07606279e-02,  2.61713183e-01,  3.60027028e-01,
         2.47957144e-01,  8.85246804e-02,  1.35206729e-01,
         1.33689333e-01,  8.08597058e-02,  2.15826226e-01,
         4.83343862e-01,  3.66865534e-01,  3.60385920e-01,
         1.20783607e-01,  3.21943321e-01,  2.82851260e-01,
         4.17243503e-01,  1.37435822e-01,  1.15545517e-01,
         6.65271809e-02,  4.43254850e-02, -2.59622163e-03,
        -4.98390617e-03,  3.70595788e-02,  6.51766002e-02,
         1.90930941e-01,  1.56206916e-01,  1.20859835e-01,
         3.99187785e-01,  2.50287700e-02,  1.98465849e-01],
       [ 3.20229979e-01,  2.88659526e-01,  1.40559898e-01,
         8.42362310e-03,  1.23763981e-01,  8.73960085e-02,
        -3.12624566e-02,  1.02092135e-02,  3.29354538e-01,
         1.13542141e-01,  7.07285082e-02,  9.75765291e-02,
         2.58001689e-01,  8.30320597e-02, -6.70866497e-02,
         1.56895919e-01,  9.77409620e-02,  1.11899942e-01,
         1.18285142e-01,  2.84377264e-01,  1.91270977e-02,
         4.65998326e-01,  1.44020091e-01,  1.34120780e-02,
         3.71968718e-02,  7.29865319e-02,  8.99345137e-02,
        -1.98787875e-02,  4.81697266e-02, -1.26702181e-02,
         2.11232638e-01,  1.55492764e-01, -7.10111505e-02,
         4.44129855e-01, -8.69022381e-02,  3.78394647e-02],
       [ 7.45386856e-02,  1.81132546e-01,  1.89032655e-01,
         1.06268330e-01,  8.06370992e-02,             nan,
                    nan, -8.64999753e-02,  2.67688225e-01,
         1.54903938e-01,  1.62731364e-01,  5.27071721e-02,
                    nan,             nan, -5.04514673e-02,
         2.83107783e-01,  1.70688582e-02, -7.00467203e-02,
                    nan,             nan, -5.22716945e-03,
         2.92295468e-01,  1.71869692e-01,             nan,
                    nan,  1.16874235e-02,  1.61645700e-01,
                    nan,             nan, -9.08952093e-02,
                    nan,             nan,             nan,
                    nan,             nan,  1.01233953e-01],
       [ 2.44947965e-01,  1.72223508e-01,  1.08552036e-01,
        -4.93020994e-02,  1.96024572e-01,  1.10576753e-01,
        -7.83132683e-02,  4.23745795e-02,  2.10555529e-01,
        -7.24071069e-02,  1.45285767e-02,  9.25322367e-02,
         2.39023819e-01,  8.98942462e-03,  1.83855699e-01,
         1.84341116e-01,  1.16445851e-01,  1.05128627e-01,
         1.08216183e-01,  4.87830907e-02,  3.56548277e-02,
         2.87675765e-01,  1.49543162e-01,  1.01352419e-01,
         1.06370195e-01,  1.46336745e-01,  1.64021356e-01,
         1.29976889e-01,  1.55469374e-01,  7.12185897e-02,
         2.06663627e-01,  1.29812621e-01,  2.53941814e-01,
         2.65343541e-01,  1.47895643e-01,  2.83442626e-01],
       [ 2.74833073e-01,  2.43847614e-01,  1.69682109e-01,
        -7.07097176e-02,  2.25860175e-01,  1.11861647e-01,
        -4.24868847e-02,  7.95715110e-03,  2.08813405e-01,
         4.50069050e-02,  2.80490643e-02,  6.61478777e-02,
         2.63099037e-01, -2.91299439e-02,  6.57088170e-02,
         3.05699369e-01,  8.58495987e-02,  2.63597695e-01,
         5.68111476e-02,  1.72898466e-01, -7.08453600e-02,
         1.55251380e-01,  4.37197659e-02,  1.03867704e-01,
        -7.99940555e-02, -4.75280390e-02,  2.38448156e-02,
         8.01886253e-02,  7.19622030e-02,  5.56492637e-02,
         2.43136950e-01,  6.61457925e-02,  2.03580461e-01,
         2.91170381e-01, -9.02763375e-02,  2.92172429e-01],
       [ 2.42924003e-01,  2.56981462e-01,  1.56038048e-01,
         6.95740018e-03,  2.30709058e-01,  1.04520786e-01,
         9.71039202e-02,  1.04401877e-01,  2.55348561e-01,
         4.20294163e-02,  1.61190030e-02,  8.95430257e-02,
         2.32269268e-01, -2.44333790e-02,  9.38228155e-02,
         2.03152155e-01,  5.30287451e-02,  2.22858645e-01,
         6.67427851e-02,  3.45439489e-01,  5.87664302e-02,
         3.41989241e-01,  7.32791198e-02,  6.94226931e-02,
        -7.39387945e-02, -1.56078019e-02,  1.87152753e-01,
        -1.04641797e-02,  2.06051179e-02,  9.67169772e-02,
         2.34272276e-01,  1.39499944e-01,  2.71893209e-02,
         3.17518610e-01, -1.22681093e-01,  1.43085113e-01],
       [ 2.13431589e-01,  8.50073741e-02,  1.95395259e-01,
        -9.90569785e-02,  2.12084433e-01,  7.20680441e-02,
         4.30790436e-02,  6.58668206e-02,  1.69685829e-01,
         1.11071208e-02, -2.63767954e-02,  1.17835697e-01,
         2.25331152e-01,  1.27752652e-01,  8.96089357e-02,
         1.93402106e-01, -1.05640052e-01,  1.36581746e-01,
         1.55071061e-01,  2.30253358e-01,  1.18952519e-01,
         4.83000119e-01,  2.77762941e-01,  1.17331701e-01,
         1.37727662e-02, -1.12627142e-01,  2.30318702e-01,
         4.52575938e-02,  8.28818933e-02,  9.85054545e-03,
         2.63778261e-01,  5.85043104e-02,  5.99980785e-02,
         2.14799458e-01,  1.99916126e-01,  2.91665919e-01],
       [ 1.36327799e-01,  2.19095123e-01,  2.55749900e-01,
         1.36060390e-01,  1.54289445e-01,             nan,
                    nan,  5.20718397e-02,  2.72858823e-01,
         2.73151316e-01,  1.49630259e-01,  1.40473960e-01,
                    nan,             nan,  4.43969401e-02,
         3.19475523e-01,  1.63276766e-01,  1.73638396e-01,
                    nan,             nan, -4.98752733e-03,
         4.25653798e-01,  2.84896248e-01,             nan,
                    nan,  2.00585688e-01,  2.19586080e-01,
                    nan,             nan,  1.37573183e-01,
                    nan,             nan,             nan,
                    nan,             nan,  2.59307142e-01],
       [ 2.81158153e-01,  2.09339222e-01,  1.91782774e-01,
         8.16804446e-02,  2.58222740e-01,  1.10450272e-01,
         1.50539205e-02,  1.19137727e-01,  2.02657708e-01,
        -3.78970698e-02,  6.40300375e-02,  8.26029458e-02,
         2.34266934e-01,  2.00316230e-01,  2.15501793e-02,
         4.23319271e-01, -1.87977948e-02,  1.70873039e-01,
        -1.43055900e-02,  1.32440650e-01, -1.27253792e-01,
         3.46152847e-01,  9.87779137e-02,  1.91750632e-01,
         8.40200567e-02,  1.34523131e-01,  1.30852882e-02,
         1.48727029e-01,  2.62032078e-02,  1.48590884e-01,
         1.85180148e-01, -2.02711330e-03,  2.65619974e-01,
         6.39725206e-01,  3.49579654e-02,  2.17927230e-01],
       [ 2.08359065e-01,  1.63377026e-01,  1.02567798e-01,
         6.49996782e-02,  1.77557498e-01,             nan,
                    nan,  6.09186714e-02,  6.14276707e-02,
         1.37831589e-02,  6.53939742e-03,  3.73833114e-02,
                    nan,             nan,  1.09813709e-02,
         2.73450859e-01,  1.15548308e-01, -5.13346776e-02,
                    nan,             nan, -7.11276427e-02,
         3.27184708e-01,  1.71277500e-01,             nan,
                    nan,  4.53086188e-02,  1.24517930e-01,
                    nan,             nan,  1.28518358e-01,
                    nan,             nan,             nan,
                    nan,             nan,  2.86449656e-01],
       [ 4.93366084e-02,  1.72299519e-01,  1.79161692e-01,
         1.03271854e-01,  5.57708383e-02,             nan,
                    nan,  3.18798395e-02,  2.42787220e-01,
         1.69128800e-01,  6.21713645e-02,  5.78217704e-03,
                    nan,             nan,  2.57456700e-02,
         4.07718186e-01,  4.90434035e-02, -2.04601257e-02,
                    nan,             nan,  1.00262929e-01,
         3.44497439e-01,  1.76786349e-01,             nan,
                    nan,  2.02066492e-02,  1.40363639e-01,
                    nan,             nan, -4.59027285e-03,
                    nan,             nan,             nan,
                    nan,             nan,  1.99942101e-01]])}

## Network SFC to DF ##

In [40]:
# List to collect merged DataFrames
df_list = []

for dataset in datasets:
    # Create column names: NSFC_network1_network2
    colnames=[]
    for i in range(len(df_network_names)):
        for j in range(i, len(df_network_names)):
#            if i>=j:
#                continue
            colnames.append(f'NSFC_{df_network_names[i]}_{df_network_names[j]}')
                
    # Create a DataFrame for the current dataset using the flattened upper triangle values
    df_ = pd.DataFrame(data_[dataset], columns=colnames)
    
    # Filter the main df_tabular by the current dataset
    df_tabular_ = df_tabular.query(f"dataset == '{dataset}'")
    
    # Add the participant_ids from the subjects
    #df_['participant_id'] = snakemake.params.subjects[dataset]
    df_['participant_id'] = ['sub-'+subject for subject in subjects[dataset]]
    
    # Merge the new df_ with df_tabular_ on 'participant_id'
    df_merged_ = pd.merge(df_tabular_, df_, how='left', on='participant_id')
    
    # Append merged DataFrame to the list
    df_list.append(df_merged_)

# Concatenate all merged DataFrames
df_tabular = pd.concat(df_list)

# Display the final DataFrame
#df_tabular_final

In [41]:
df_tabular

,participant_id,dataset,age,sex,age_seizure_onset,age_ep_diagnosis,ep_duration_first_scan,seizure_duration_first_scan,pnes,benign_rolandic,...,NSFC_SalVentAttn_SalVentAttn,NSFC_SalVentAttn_Limbic_y,NSFC_SalVentAttn_Vis_y,NSFC_SalVentAttn_Subcort_y,NSFC_Limbic_Limbic,NSFC_Limbic_Vis_y,NSFC_Limbic_Subcort_y,NSFC_Vis_Vis,NSFC_Vis_Subcort_y,NSFC_Subcort_Subcort
0,sub-HCD0001305,HCP,11.916667,M,NaN,NaN,NaN,NaN,NaN,NaN,...,-0.051514,-0.037687,0.081986,0.021659,0.230121,0.136540,0.172306,0.391232,0.235832,0.222772
1,sub-HCD0021614,HCP,9.166667,F,NaN,NaN,NaN,NaN,NaN,NaN,...,0.191769,0.140698,0.171308,0.120894,0.060736,0.054325,0.020776,0.299988,-0.024940,0.152559
2,sub-HCD0026119,HCP,15.166667,F,NaN,NaN,NaN,NaN,NaN,NaN,...,0.059738,-0.038915,0.007031,-0.003325,0.201541,0.087527,0.037533,0.284650,0.078022,0.251963
3,sub-HCD0041822,HCP,17.416667,M,NaN,NaN,NaN,NaN,NaN,NaN,...,0.215305,-0.048796,0.133589,0.169853,0.362428,0.147484,0.193413,0.460991,0.077882,0.307386
4,sub-HCD0042420,HCP,18.333333,M,NaN,NaN,NaN,NaN,NaN,NaN,...,0.157569,0.115009,0.070474,0.091282,0.191039,0.130871,0.090061,0.459049,0.052822,0.177362
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22,sub-035,LOBE,7.000000,M,2.0,4.0,3.0,5.0,0.0,0.0,...,0.230319,0.045258,0.082882,0.009851,0.263778,0.058504,0.059998,0.214799,0.199916,0.291666
23,sub-036,LOBE,15.000000,M,10.0,NaN,NaN,5.0,NaN,NaN,...,0.219586,NaN,NaN,0.137573,NaN,NaN,NaN,NaN,NaN,0.259307
24,sub-038,LOBE,10.000000,F,7.0,7.0,3.0,3.0,0.0,0.0,...,0.013085,0.148727,0.026203,0.148591,0.185180,-0.002027,0.265620,0.639725,0.034958,0.217927
25,sub-040,LOBE,9.000000,F,5.0,NaN,NaN,4.0,NaN,NaN,...,0.124518,NaN,NaN,0.128518,NaN,NaN,NaN,NaN,NaN,0.286450
26,sub-041,LOBE,12.000000,M,4.0,NaN,NaN,8.0,NaN,NaN,...,0.140364,NaN,NaN,-0.004590,NaN,NaN,NaN,NaN,NaN,0.199942

# Network FC #

In [42]:
data_={}
for dataset in ['HCP','LOBE']:

    x1 = fc[dataset]
#    data_[dataset] = np.zeros((x1.shape[0],int((num_parcels*(num_parcels+1))/2)-num_parcels)) #if excluding diagonal
    data_[dataset] = np.zeros((x1.shape[0],int((num_parcels*(num_parcels+1))/2)))
    num_parcels = x1.shape[1]  # Assuming it's 8

    # Loop over each "slice" in x2 (assuming only one slice, so loop over the first element)
    for s in range(x1.shape[0]):
        conn = x1[s, :, :]  # Extract the 8x8 matrix for the current subject        
        # Now loop over the upper triangle to gather values for each "mixture"
        values_subj=[]
        for i in range(num_parcels):
            for j in range(i, num_parcels): # Include diagonal as well by starting at i
                # You are looking at the upper triangular part (i < j)
                # This will collect values from (i, j) where i < j
                #if j>i:
               values_subj.append(conn[i, j])  # Get the value for that specific pair (i, j)
    
        data_[dataset][s,:] = values_subj

## Network FC to DF ##

In [43]:
# List to collect merged DataFrames
df_list = []

for dataset in datasets:
    # Create column names: NSFC_network1_network2
    colnames=[]
    for i in range(len(df_network_names)):
        for j in range(i, len(df_network_names)):
#            if i>=j:
#                continue
            colnames.append(f'NFC_{df_network_names[i]}_{df_network_names[j]}')
                
    # Create a DataFrame for the current dataset using the flattened upper triangle values
    df_ = pd.DataFrame(data_[dataset], columns=colnames)
    
    # Filter the main df_tabular by the current dataset
    df_tabular_ = df_tabular.query(f"dataset == '{dataset}'")
    
    # Add the participant_ids from the subjects
    #df_['participant_id'] = snakemake.params.subjects[dataset]
    df_['participant_id'] = ['sub-'+subject for subject in subjects[dataset]]
    
    # Merge the new df_ with df_tabular_ on 'participant_id'
    df_merged_ = pd.merge(df_tabular_, df_, how='left', on='participant_id')
    
    # Append merged DataFrame to the list
    df_list.append(df_merged_)

# Concatenate all merged DataFrames
df_tabular = pd.concat(df_list)

In [44]:
print(df_tabular)

    participant_id dataset        age sex  age_seizure_onset  \
0   sub-HCD0001305     HCP  11.916667   M                NaN
1   sub-HCD0021614     HCP   9.166667   F                NaN
2   sub-HCD0026119     HCP  15.166667   F                NaN
3   sub-HCD0041822     HCP  17.416667   M                NaN
4   sub-HCD0042420     HCP  18.333333   M                NaN
..             ...     ...        ...  ..                ...
22         sub-035    LOBE   7.000000   M                2.0
23         sub-036    LOBE  15.000000   M               10.0
24         sub-038    LOBE  10.000000   F                7.0
25         sub-040    LOBE   9.000000   F                5.0
26         sub-041    LOBE  12.000000   M                4.0

    age_ep_diagnosis  ep_duration_first_scan  seizure_duration_first_scan  \
0                NaN                     NaN                          NaN
1                NaN                     NaN                          NaN
2                NaN                     NaN                          NaN
3                NaN                     NaN                          NaN
4                NaN                     NaN                          NaN
..               ...                     ...                          ...
22               4.0                     3.0                          5.0
23               NaN                     NaN                          5.0
24               7.0                     3.0                          3.0
25               NaN                     NaN                          4.0
26               NaN                     NaN                          8.0

    pnes  benign_rolandic  ... NFC_SalVentAttn_SalVentAttn  \
0    NaN              NaN  ...                    0.455056
1    NaN              NaN  ...                    0.551172
2    NaN              NaN  ...                    0.374364
3    NaN              NaN  ...                    0.402316
4    NaN              NaN  ...                    0.377566
..   ...              ...  ...                         ...
22   0.0              0.0  ...                    0.276463
23   NaN              NaN  ...                    0.067090
24   0.0              0.0  ...                    0.341050
25   NaN              NaN  ...                    0.298101
26   NaN              NaN  ...                    0.355021

    NFC_SalVentAttn_Limbic  NFC_SalVentAttn_Vis  NFC_SalVentAttn_Subcort  \
0                 0.247070             0.163983                 0.217727
1                -0.002954             0.040074                 0.377734
2                -0.024572             0.010875                -0.018716
3                -0.091443            -0.028720                 0.199181
4                 0.085077             0.241052                 0.145810
..                     ...                  ...                      ...
22               -0.046076             0.025847                -0.001154
23                     NaN                  NaN                 0.046194
24                0.054332             0.271682                 0.136510
25                     NaN                  NaN                 0.230683
26                     NaN                  NaN                 0.155159

    NFC_Limbic_Limbic  NFC_Limbic_Vis  NFC_Limbic_Subcort  NFC_Vis_Vis  \
0            0.295966        0.082092            0.216913     0.573104
1            0.102516        0.014798            0.039081     0.536552
2            0.219067        0.211553            0.126168     0.332539
3            0.187178        0.094875            0.043094     0.524937
4            0.136923        0.065211            0.080045     0.458136
..                ...             ...                 ...          ...
22           0.110809        0.070548            0.007470     0.458385
23                NaN             NaN                 NaN          NaN
24           0.153855        0.047145            0.118392     0.569638
25                NaN             NaN                 NaN          NaN
26                NaN             NaN                 NaN          NaN

    NFC_Vis_Subcort  NFC_Subcort_Subcort
0          0.003145             0.260267
1          0.181319             0.336474
2          0.097814             0.249803
3          0.144953             0.243698
4          0.100699             0.165530
..              ...                  ...
22         0.018218             0.086504
23              NaN             0.145833
24         0.273706             0.265090
25              NaN             0.216793
26              NaN             0.159316

[368 rows x 895 columns]

# Network SC #

In [45]:
data_={}
for dataset in ['HCP','LOBE']:

    x1 = sc[dataset]
#    data_[dataset] = np.zeros((x1.shape[0],int((num_parcels*(num_parcels+1))/2)-num_parcels)) #if excluding diagonal
    data_[dataset] = np.zeros((x1.shape[0],int((num_parcels*(num_parcels+1))/2)))
    num_parcels = x1.shape[1]  # Assuming it's 8

    # Loop over each "slice" in x2 (assuming only one slice, so loop over the first element)
    for s in range(x1.shape[0]):
        conn = x1[s, :, :]  # Extract the 8x8 matrix for the current subject        
        # Now loop over the upper triangle to gather values for each "mixture"
        values_subj=[]
        for i in range(num_parcels):
            for j in range(i, num_parcels): # Include diagonal as well by starting at i
                # You are looking at the upper triangular part (i < j)
                # This will collect values from (i, j) where i < j
                #if j>i:
               values_subj.append(conn[i, j])  # Get the value for that specific pair (i, j)
    
        data_[dataset][s,:] = values_subj

## Network SC to DF ##

In [46]:
# List to collect merged DataFrames
df_list = []

for dataset in datasets:
    # Create column names: NSFC_network1_network2
    colnames=[]
    for i in range(len(df_network_names)):
        for j in range(i, len(df_network_names)):
#            if i>=j:
#                continue
            colnames.append(f'NSC_{df_network_names[i]}_{df_network_names[j]}')
                
    # Create a DataFrame for the current dataset using the flattened upper triangle values
    df_ = pd.DataFrame(data_[dataset], columns=colnames)
    
    # Filter the main df_tabular by the current dataset
    df_tabular_ = df_tabular.query(f"dataset == '{dataset}'")
    
    # Add the participant_ids from the subjects
    #df_['participant_id'] = snakemake.params.subjects[dataset]
    df_['participant_id'] = ['sub-'+subject for subject in subjects[dataset]]
    
    # Merge the new df_ with df_tabular_ on 'participant_id'
    df_merged_ = pd.merge(df_tabular_, df_, how='left', on='participant_id')
    
    # Append merged DataFrame to the list
    df_list.append(df_merged_)

# Concatenate all merged DataFrames
df_tabular = pd.concat(df_list)

In [47]:
df_tabular

,participant_id,dataset,age,sex,age_seizure_onset,age_ep_diagnosis,ep_duration_first_scan,seizure_duration_first_scan,pnes,benign_rolandic,...,NSC_SalVentAttn_SalVentAttn,NSC_SalVentAttn_Limbic,NSC_SalVentAttn_Vis,NSC_SalVentAttn_Subcort,NSC_Limbic_Limbic,NSC_Limbic_Vis,NSC_Limbic_Subcort,NSC_Vis_Vis,NSC_Vis_Subcort,NSC_Subcort_Subcort
0,sub-HCD0001305,HCP,11.916667,M,NaN,NaN,NaN,NaN,NaN,NaN,...,40.757391,2.975919,2.597584,5.241213,28.047255,10.010869,13.298278,105.752711,5.953540,19.546977
1,sub-HCD0021614,HCP,9.166667,F,NaN,NaN,NaN,NaN,NaN,NaN,...,39.413017,4.171387,2.245926,4.598027,32.891039,12.078563,13.234206,105.403053,6.463169,22.100373
2,sub-HCD0026119,HCP,15.166667,F,NaN,NaN,NaN,NaN,NaN,NaN,...,44.295020,2.556438,2.610421,6.660333,34.077937,11.217109,13.891990,104.834428,6.156265,17.931060
3,sub-HCD0041822,HCP,17.416667,M,NaN,NaN,NaN,NaN,NaN,NaN,...,46.129693,3.966129,2.188160,6.850904,33.457747,11.132245,12.269200,97.801502,6.315147,16.640446
4,sub-HCD0042420,HCP,18.333333,M,NaN,NaN,NaN,NaN,NaN,NaN,...,42.346860,2.115234,1.846729,6.983856,22.655861,11.467509,12.633637,123.476313,8.169264,22.466293
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22,sub-035,LOBE,7.000000,M,2.0,4.0,3.0,5.0,0.0,0.0,...,39.664197,2.319370,2.122028,6.472531,23.968392,10.809864,14.499692,102.175874,6.783984,20.863529
23,sub-036,LOBE,15.000000,M,10.0,NaN,NaN,5.0,NaN,NaN,...,36.628466,4.651603,7.060361,9.351755,23.039414,8.531045,9.941072,77.090335,7.339646,17.727574
24,sub-038,LOBE,10.000000,F,7.0,7.0,3.0,3.0,0.0,0.0,...,43.181745,2.159854,1.639886,6.830392,23.902955,10.153906,13.432425,124.298370,5.640846,22.563577
25,sub-040,LOBE,9.000000,F,5.0,NaN,NaN,4.0,NaN,NaN,...,34.462462,5.122824,5.519767,11.760260,22.540144,7.109691,11.569769,57.722866,6.162687,20.974136
26,sub-041,LOBE,12.000000,M,4.0,NaN,NaN,8.0,NaN,NaN,...,39.370669,5.268788,5.223478,10.711617,22.795966,6.671885,11.109369,76.563848,7.064120,19.512251

## Save regional and network SFC, SC & FC to masterlist ##

In [309]:
#df_tabular.to_csv(snakemake.output.tsv,sep='\t',index=False)
df_tabular.to_csv('resources/merged_tabular_withconn.tsv',sep='\t',index=False)

df_tabular

,participant_id,dataset,age,sex,age_seizure_onset,age_ep_diagnosis,ep_duration_first_scan,seizure_duration_first_scan,pnes,benign_rolandic,...,NSC_SomMot_SalVentAttn,NSC_SomMot_Limbic,NSC_SomMot_Vis,NSC_SomMot_Subcort,NSC_SalVentAttn_Limbic,NSC_SalVentAttn_Vis,NSC_SalVentAttn_Subcort,NSC_Limbic_Vis,NSC_Limbic_Subcort,NSC_Vis_Subcort
0,sub-006,LOBE,9.000000,M,7.0,8.0,1.0,2.0,0.0,0.0,...,31.775043,6.093779,3.565853,13.678539,2.441071,2.329315,8.072034,11.253556,12.779200,6.692866
1,sub-007,LOBE,9.000000,F,7.0,7.0,2.0,2.0,0.0,0.0,...,31.047608,4.694701,3.856497,15.089026,3.376797,2.284875,7.104348,12.902451,11.629192,8.165592
2,sub-009,LOBE,8.000000,M,2.0,8.0,0.0,6.0,0.0,0.0,...,32.139420,6.092804,3.411451,13.488859,2.429249,1.973247,5.597904,14.113860,14.490517,6.861490
3,sub-010,LOBE,15.000000,M,7.0,7.0,8.0,8.0,0.0,0.0,...,29.912222,7.515808,3.188353,15.295826,3.096588,1.656353,7.481329,12.360719,15.176665,7.871957
4,sub-012,LOBE,14.000000,F,4.0,10.0,4.0,10.0,0.0,0.0,...,32.515501,4.926970,4.040693,16.702632,1.993364,2.197655,7.719997,11.074222,13.349639,6.167509
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
336,sub-HCD2939275,HCP,16.250000,F,NaN,NaN,NaN,NaN,NaN,NaN,...,26.265281,5.570720,4.080949,18.933459,2.370305,2.589226,8.747184,10.918745,12.261460,6.856109
337,sub-HCD2945876,HCP,12.000000,M,NaN,NaN,NaN,NaN,NaN,NaN,...,31.226796,5.803166,4.120753,13.603780,2.159014,2.317764,7.185076,11.754142,12.527781,5.330596
338,sub-HCD2957277,HCP,17.416667,F,NaN,NaN,NaN,NaN,NaN,NaN,...,26.532396,5.735926,3.784627,17.729031,3.972132,2.707440,11.851276,12.766131,14.714072,7.540711
339,sub-HCD2976382,HCP,11.333333,M,NaN,NaN,NaN,NaN,NaN,NaN,...,33.353692,6.154235,3.952284,15.130180,3.102931,2.191105,9.302829,9.586851,13.520166,6.838586
340,sub-HCD2990073,HCP,13.583333,F,NaN,NaN,NaN,NaN,NaN,NaN,...,30.152925,5.931777,4.360665,16.144681,4.237848,2.996272,7.505482,10.341930,12.437066,7.429819